### ISSUE TITLE
Installing Error in Raspberry Pi 2

### ISSUE THREAD

**Issue by erivandoramos** [ageitgey/face_recognition#102]
* face_recognition version: 0.1.0 (current)
* Python version: 2.7
* Operating System: Raspbian Jessie

### Description

After all the prerequisites were installed, And all right with dlib, dlib is running properly, it's ok!
I started the installation of Face Recognition and at 99% of the installation install to with an exception and error.

### What I Did
Installed dlib from source successfully
and
I increased the memory Swap to 10G;

```
pi@raspberrypi:~/face_recognition $ sudo pip2 install face_recognition
Collecting face_recognition
  Using cached face_recognition-0.1.14-py2.py3-none-any.whl
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from face_recognition)
Requirement already satisfied: dlib>=19.3.0 in /usr/local/lib/python2.7/dist-packages/dlib-19.4.99-py2.7-linux-armv7l.egg (from face_recognition)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from face_recognition)
Collecting face-recognition-models (from face_recognition)
  Downloading face_recognition_models-0.1.3-py2.py3-none-any.whl (93.3MB)
    99% |████████████████████████████████| 93.3MB 11kB/s eta 0:00:01Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 882, in _download_http_url
    _download_url(resp, link, content_file, hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 603, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/hashes.py", line 46, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 571, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/ui.py", line 139, in iter
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 560, in resp_read
    decode_content=False):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 63, in read
    self._close()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 50, in _close
    self.__callback(self.__buf.getvalue())
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/controller.py", line 275, in cache_response
    self.serializer.dumps(request, response, body=body),
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/cachecontrol/serialize.py", line 87, in dumps
    ).encode("utf8"),
MemoryError

```

**Comment by ageitgey** [comment]
This is a python2/pip issue covered in the README under [Common Issues](https://github.com/ageitgey/face_recognition#common-issues).

**Comment by erivandoramos** [comment]
Thanks ageitgey

**Comment by ageitgey** [comment]
No problem!
