### ISSUE TITLE
Test face_recognition TypeError: imread() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by erivandoramos** [ageitgey/face_recognition#103]
* face_recognition version: 0.1.14
* Python version: 2.7
* Operating System: Raspbian Jessie

### Description

When trying to run the example code below:
```
import face_recognition

picture_of_me = face_recognition.load_image_file("/home/pi/Imagem.jpg"")
my_face_encoding = face_recognition.face_encodings(picture_of_me)[0]

# my_face_encoding now contains a universal 'encoding' of my facial features that can be compared to any other picture of a face!
unknown_picture = face_recognition.load_image_file("/home/pi/Imagem1.jpg"")
unknown_face_encoding = face_recognition.face_encodings(unknown_picture)[0]

# Now we can see the two face encodings are of the same person with `compare_faces`!
results = face_recognition.compare_faces([my_face_encoding], unknown_face_encoding)

if results[0] == True:
    print("It's a picture of me!")
else:
    print("It's not a picture of me!")
```
### What I Did
I did the scipy update, but, the error continued.
```

pi@raspberrypi:~ $ pip show scipy
Name: scipy
Version: 0.19.0
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: SciPy Developers
Author-email: scipy-dev@scipy.org
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires: numpy
```

How are you now:
```
pi@raspberrypi:~/face_recognition $ sudo pip2 install --upgrade face_recognition
Requirement already up-to-date: face_recognition in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages (from face_recognition)
Requirement already up-to-date: dlib>=19.3.0 in /usr/local/lib/python2.7/dist-packages/dlib-19.4.99-py2.7-linux-armv7l.egg (from face_recognition)
Requirement already up-to-date: numpy in /usr/local/lib/python2.7/dist-packages (from face_recognition)
Requirement already up-to-date: face-recognition-models in /usr/local/lib/python2.7/dist-packages (from face_recognition)
Requirement already up-to-date: Click>=6.0 in /usr/local/lib/python2.7/dist-packages (from face_recognition)
Requirement already up-to-date: scipy>=0.17.0 in /usr/local/lib/python2.7/dist-packages (from face_recognition)
Requirement already up-to-date: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->face_recognition)
```

Test:
```
pi@raspberrypi:~ $ sudo python reconhece_face.py
Traceback (most recent call last):
  File "reconhece_face.py", line 6, in <module>
    picture_of_me = face_recognition.load_image_file("/home/pi/Imagem.jpg")
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 78, in load_image_file
    return scipy.misc.imread(filename, mode=mode)
TypeError: imread() got an unexpected keyword argument 'mode'
```

**Comment by BalajiB3663** [comment]
Hi @erivandoramos , the code working fine and accurate. Please check with the installation. 
I have tried similar samples of examples also. (y)

**Comment by ageitgey** [comment]
This is covered in the README under [Common Issues](https://github.com/ageitgey/face_recognition#common-issues).

Issue: TypeError: imread() got an unexpected keyword argument 'mode'

Solution: The version of scipy you have installed is too old. You need version 0.17 or newer. Upgrade scipy.

**Comment by ageitgey** [comment]
Is it possible that you had installed scipy first via apt-get and there's still a rogue copy of an old scipy installed? If so, the apt-get version from debian jessie would be too old. You could try:

`apt-get remove --purge python-scipy`

**Comment by erivandoramos** [comment]
Hi @ageitgey 
Thank you

It was true, there was.

```
pi@raspberrypi:~ $ sudo apt-get remove --purge python-scipy
Lendo listas de pacotes... Pronto
Construindo árvore de dependências
Lendo informação de estado... Pronto
Os pacotes a seguir serão REMOVIDOS:
  python-scipy*
0 pacotes atualizados, 0 pacotes novos instalados, 1 a serem removidos e 0 não atualizados.
Depois desta operação, 28,9 MB de espaço em disco serão liberados.
Você quer continuar? [S/n] S
(Lendo banco de dados ... 97871 ficheiros e directórios actualmente instalados.)
A remover python-scipy (0.14.0-2) ...
```

I think now everything is correct, just fall into this error below, but I think it is a programming error ...
```
pi@raspberrypi:~ $ sudo python reconhece_face.py
Traceback (most recent call last):
  File "reconhece_face.py", line 7, in <module>
    my_face_encoding = face_recognition.face_encodings(picture_of_me)[0]
IndexError: list index out of range
```

**Comment by ageitgey** [comment]
Yep, that just means that no face was detected in "picture_of_me" so there's no `[0]` element in the array.  

Just do something like:

```python 
encodings = face_recognition.face_encodings(picture_of_me)
if len(encodings) > 0:
  my_face_encoding = encodings[0]
else:
  print("No face detected in the picture! Quitting!")
  quit()
```
.. or whatever
