### ISSUE TITLE
PHP shell_exec and face_detection

### ISSUE THREAD

**Issue by kko123** [ageitgey/face_recognition#1070]
* face_recognition version: latest
* Python version: 2.7.13
* Operating System: linux

### Description
var_dump(shell_exec("/usr/local/bin/face_detection 1.jpg"));
always return NULL, but the same command works in terminal
how i can link face_detection and PHP?
I always try to use the absolute path to face_detection and jpg, but no success!
P/S. Got error: Traceback (most recent call last): File "/usr/local/bin/face_detection", line 11, in sys.exit(main()) File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main _verify_python3_env() File "/usr/local/lib/python3.5/dist-packages/click/_unicodefun.py", line 124, in _verify_python3_env ' mitigation steps.' + extra RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps. This system supports the C.UTF-8 locale which is recommended. You might be able to resolve your issue by exporting the following environment variables: export LC_ALL=C.UTF-8 export LANG=C.UTF-8
LC_ALL=C.UTF-8 and LANG=C.UTF-8 always in .env

**Comment by kko123** [comment]
Solved, CLI and Apache used different environment
