### ISSUE TITLE
 File "facerec_from_video_file.py", line 86, in <module>     cv2.destroyAllWindows() cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:626: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

### ISSUE THREAD

**Issue by tim94173** [ageitgey/face_recognition#1108]
first time i ran `pythonfacerec _from_video_file.py` successfully and i enter` ctrl+c`to stop , but second time i ran `python facerec_from_video_file.py` and it showed :

Traceback (most recent call last):
File "facerec_from_video_file.py", line 86, in
cv2.destroyAllWindows()
cv2.error: OpenCV(3.4.2) /tmp/build/80754af9/opencv-suite_1535558553474/work/modules/highgui/src/window.cpp:626: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

what happened??

**Comment by thoangnguyen1308** [comment]
how to project?
I borrow to see. my english is not good i use google
 Thanks.

Vào Th 7, 11 thg 4, 2020 vào lúc 01:14 tim94173 <notifications@github.com>
đã viết:
