### ISSUE TITLE
running example error

### ISSUE THREAD

**Issue by shook2012** [ageitgey/face_recognition#1111]
* face_recognition version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
When I run the example of copy face_recognition_knn.py, I encountered an error:

Training KNN classifier...
Traceback (most recent call last):
  File "my_knn.py", line 188, in <module>
    classifier = train("imagelib", model_save_path="trained_knn_model_my.clf", n_neighbors=2)
  File "my_knn.py", line 101, in train
    knn_clf.fit(X, y)
  File "/usr/local/python3/lib/python3.8/site-packages/sklearn/neighbors/_base.py", line 1126, in fit
    X, y = check_X_y(X, y, "csr", multi_output=True)
  File "/usr/local/python3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 747, in check_X_y
    X = check_array(X, accept_sparse=accept_sparse,
  File "/usr/local/python3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 552, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].

```

**Comment by sandipnd31** [comment]
I am facing same issue, any solution

**Comment by sandipnd31** [comment]
@shook2012  please help me if u got any solution
