### ISSUE TITLE
PyInstaller + face_recognition Exe Runtime Error

### ISSUE THREAD

**Issue by SamratSahoo** [ageitgey/face_recognition#1116]
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description
I was trying to execute an exe file I had made using PyInstaller that utilized the face_recognition library. Unfortunately when executing the file, I got a Runtime Error. I saw a similar error ([#628](https://github.com/ageitgey/face_recognition/issues/628)) which told me to install the models but after running```pip install face_recognition_models``` and remaking the exe, I am still getting this error.

**Error:**
```
RuntimeError: Unable to open /tmp/_MEIJebbbx/face_recognition_models/models/shape_predictor_68_face_landmarks.dat
````

**Full Error Message:**

```
Traceback (most recent call last):
  File "Interface.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "Camera.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "face_recognition/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "face_recognition/api.py", line 20, in <module>
RuntimeError: Unable to open /tmp/_MEI4LEO3U/face_recognition_models/models/shape_predictor_68_face_landmarks.dat
[9073] Failed to execute script Interface
```
Any and all insight is appreciated. Thanks!

**Comment by Latestion** [comment]
It is just - pip install face_recognition. I think.

**Comment by SamratSahoo** [comment]
> It is just - pip install face_recognition. I think.

In order to install the face_recognition library (which I have already done) you need ```pip install face_recognition``` However, the error message says it cannot open face_recognition_models and so I pip installed the models as well but it is still throwing the error

**Comment by WenBoNie** [comment]
I have this problem, too 。  help!

**Comment by canpltt** [comment]
Can you fix that?

**Comment by ranarashid426** [comment]
> * Python version: 3.6
> * Operating System: Ubuntu 18.04
> 
> ### Description
> I was trying to execute an exe file I had made using PyInstaller that utilized the face_recognition library. Unfortunately when executing the file, I got a Runtime Error. I saw a similar error ([#628](https://github.com/ageitgey/face_recognition/issues/628)) which told me to install the models but after running`pip install face_recognition_models` and remaking the exe, I am still getting this error.
> 
> **Error:**
> 
> ```
> RuntimeError: Unable to open /tmp/_MEIJebbbx/face_recognition_models/models/shape_predictor_68_face_landmarks.dat
> ```
> 
> **Full Error Message:**
> 
> ```
> Traceback (most recent call last):
>   File "Interface.py", line 6, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
>     exec(bytecode, module.__dict__)
>   File "Camera.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
>     exec(bytecode, module.__dict__)
>   File "face_recognition/__init__.py", line 7, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "/home/samrat/Documents/Facial-Recognition-Attendance-Tracker/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
>     exec(bytecode, module.__dict__)
>   File "face_recognition/api.py", line 20, in <module>
> RuntimeError: Unable to open /tmp/_MEI4LEO3U/face_recognition_models/models/shape_predictor_68_face_landmarks.dat
> [9073] Failed to execute script Interface
> ```
> 
> Any and all insight is appreciated. Thanks!

Did you find any solution?

**Comment by boogaming** [comment]
Use pyinstaller -c PyFileName.py (with console) or pyinstaller -w PyFileName.py (without console) instead of pyinstaller --onefile PyFileName.py. Then add folder containing face_recognition models .dat files. Example, "face_recognition_models/models/shape_predictor_68_face_landmarks.dat" in the same folder of the executable file.
