### ISSUE TITLE
Getting error while installing sparse module

### ISSUE THREAD

**Issue by harshitKyal** [ageitgey/face_recognition#1122]
* face_recognition version: 
* Python version:2.7
* Operating System: macOS Catalina version 10.15.3

### Description
I am trying to run face_recognition on my system. Installing sparse Module getting error.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting sparse
  Using cached sparse-0.6.0-py2.py3-none-any.whl (47 kB)
Requirement already satisfied: numpy>=1.13 in /Users/varungupta/Library/Python/2.7/lib/python/site-packages (from sparse) (1.16.6)
Requirement already satisfied: scipy>=0.19 in /Users/varungupta/Library/Python/2.7/lib/python/site-packages (from sparse) (1.2.2)
Collecting numba>=0.39
  Using cached numba-0.47.0-cp27-cp27m-macosx_10_9_x86_64.whl (2.0 MB)
Requirement already satisfied: funcsigs; python_version < "3.3" in /Users/varungupta/Library/Python/2.7/lib/python/site-packages (from numba>=0.39->sparse) (1.0.2)
Collecting llvmlite>=0.31.0dev0
  Using cached llvmlite-0.32.0.tar.gz (103 kB)
Requirement already satisfied: enum34; python_version < "3.4" in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from numba>=0.39->sparse) (1.1.6)
Requirement already satisfied: singledispatch; python_version < "3.4" in /Users/varungupta/Library/Python/2.7/lib/python/site-packages (from numba>=0.39->sparse) (3.4.0.3)
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from numba>=0.39->sparse) (41.0.1)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from singledispatch; python_version < "3.4"->numba>=0.39->sparse) (1.12.0)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-wheel-Enug0e
       cwd: /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/
  Complete output (11 lines):
  running bdist_wheel
  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py", line 168, in <module>
      main()
    File "/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py", line 162, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: /usr/bin/llvm-config-6.0 failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, sparse
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-record-tz529G/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/varungupta/Library/Python/2.7/include/python2.7/llvmlite
         cwd: /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/
    Complete output (14 lines):
    running install
    running build
    got version from file /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/llvmlite/_version.py {'version': '0.32.0', 'full': '26059d238f4ba23dff74703dd27168591d889edd'}
    running build_ext
    /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py", line 168, in <module>
        main()
      File "/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py", line 162, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: /usr/bin/llvm-config-6.0 failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-install-lsxU6M/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/mn/rgnylh413g96j9x5vjs4rtx80000gn/T/pip-record-tz529G/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/varungupta/Library/Python/2.7/include/python2.7/llvmlite Check the logs for full command output.

Also I clone this repo on my system . Do i need to install every module one by one ? is there any command to install all module alltogether ? I am new to python.

**Comment by pranavhari2** [comment]
I think it says you need python version 3.3 or higher.
