### ISSUE TITLE
face_recognition won't install

### ISSUE THREAD

**Issue by Koushiq** [ageitgey/face_recognition#1212]
* face_recognition version: 1.2.3
* Python version:3.8.2
* Operating System:Ubuntu Mate ( For Raspberry pi  ) 

I am trying to install face recognition on various 64 bit OS for raspberry pi , but for every os i've tried , face recognition just wont install except for the 32 bit raspberry pi os itself 

This is the command I am using the following command , ( cmake is installed ) 

sudo pip3  install face_recognition
Collecting face_recognition
  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)
Processing /root/.cache/pip/wheels/d6/81/3c/884bcd5e1c120ff548d57c2ecc9ebf3281c9a6f7c0e7e7947a/face_recognition_models-0.3.0-py2.py3-none-any.whl
Collecting numpy
  Using cached numpy-1.19.2-cp37-cp37m-manylinux2014_aarch64.whl (12.2 MB)
Requirement already satisfied: Click>=6.0 in /usr/lib/python3/dist-packages (from face_recognition) (7.0)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition) (7.0.0)
Collecting dlib>=19.7
  Using cached dlib-19.21.0.tar.gz (3.2 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z8b1z3_o/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z8b1z3_o/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jgryz20m
       cwd: /tmp/pip-install-z8b1z3_o/dlib/
  Complete output (40 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-z8b1z3_o/dlib/setup.py", line 262, in <module>
      'Topic :: Software Development',
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-z8b1z3_o/dlib/setup.py", line 129, in run
      cmake_version = self.get_cmake_version()
    File "/tmp/pip-install-z8b1z3_o/dlib/setup.py", line 120, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 245.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: face-recognition-models, numpy, dlib, face-recognition
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z8b1z3_o/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z8b1z3_o/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qtzxda3h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.7m/dlib
         cwd: /tmp/pip-install-z8b1z3_o/dlib/
    Complete output (42 lines):
    running install
    running build
    running build_py
    package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z8b1z3_o/dlib/setup.py", line 262, in <module>
        'Topic :: Software Development',
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-z8b1z3_o/dlib/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/tmp/pip-install-z8b1z3_o/dlib/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 245.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z8b1z3_o/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z8b1z3_o/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-qtzxda3h/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.7m/dlib Check the logs for full command output.

**Comment by KiLJ4EdeN** [comment]
Hello
Have you tried wheels from

https://www.piwheels.org/simple/dlib/

**Comment by Marchel-Ace** [comment]
try update your pip and setup-tools

**Comment by yashasvi-sakure** [comment]
hey!
if you are installing the things from visual studio code terminal make sure you have visual studio community installed as this sometimes create errors in smooth installation.

**Comment by pejamns21** [comment]
I use anaconda to install and run .
And i didn't get any error
