### ISSUE TITLE
Error while calling cudaMalloc Out of memory

### ISSUE THREAD

**Issue by fspider** [ageitgey/face_recognition#1253]
* face_recognition version: face_recognition 1.3.0  face_recognition_model 0.3.0
* Python version: Python3.6
* Operating System: Ubuntu 18.04
* RTX 3090, tf-nightly-gpu 2.5.0, cuda11.1, cudnn 8005

### Description
Running with darknet , deepsort, face_recognition

After 1 mins running, it stuck here.

```
Traceback (most recent call last):
  File "sportscamera.py", line 162, in <module>
    sportscamera.start()
  File "sportscamera.py", line 68, in start
    self.process_persons(image, persons)
  File "sportscamera.py", line 121, in process_persons
    face_location = self.faceTracker.detectFace(person_img)
  File "/home/troica/WORK/SportsCamera/utils/face_tracker.py", line 15, in detectFace
    face_locations = self.detectFaces(frame, show=False)
  File "/home/troica/WORK/SportsCamera/utils/face_tracker.py", line 21, in detectFaces
    face_locations = face_recognition.face_locations(frame, model="cnn")
  File "/home/troica/anaconda3/envs/test_36/lib/python3.6/site-packages/face_recognition/api.py", line 119, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "/home/troica/anaconda3/envs/test_36/lib/python3.6/site-packages/face_recognition/api.py", line 103, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /tmp/pip-install-p7ke4hs2/dlib_5e1a223c72b742d8a632bfbb7f0f2e5a/dlib/cuda/gpu_data.cpp:221. code: 2, reason: out of memory
```

**Comment by KiLJ4EdeN** [comment]
> * face_recognition version: face_recognition 1.3.0  face_recognition_model 0.3.0
> * Python version: Python3.6
> * Operating System: Ubuntu 18.04
> * RTX 3090, tf-nightly-gpu 2.5.0, cuda11.1, cudnn 8005
> 
> ### Description
> Running with darknet , deepsort, face_recognition
> 
> After 1 mins running, it stuck here.
> 
> ```
> Traceback (most recent call last):
>   File "sportscamera.py", line 162, in <module>
>     sportscamera.start()
>   File "sportscamera.py", line 68, in start
>     self.process_persons(image, persons)
>   File "sportscamera.py", line 121, in process_persons
>     face_location = self.faceTracker.detectFace(person_img)
>   File "/home/troica/WORK/SportsCamera/utils/face_tracker.py", line 15, in detectFace
>     face_locations = self.detectFaces(frame, show=False)
>   File "/home/troica/WORK/SportsCamera/utils/face_tracker.py", line 21, in detectFaces
>     face_locations = face_recognition.face_locations(frame, model="cnn")
>   File "/home/troica/anaconda3/envs/test_36/lib/python3.6/site-packages/face_recognition/api.py", line 119, in face_locations
>     return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
>   File "/home/troica/anaconda3/envs/test_36/lib/python3.6/site-packages/face_recognition/api.py", line 103, in _raw_face_locations
>     return cnn_face_detector(img, number_of_times_to_upsample)
> RuntimeError: Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /tmp/pip-install-p7ke4hs2/dlib_5e1a223c72b742d8a632bfbb7f0f2e5a/dlib/cuda/gpu_data.cpp:221. code: 2, reason: out of memory
> ```

Hello,

As the error indicates you went out of memory,
consider that wheb using CUDA only gpu memory can be used, and according to some tests i did before, lower than 4GB of ram might not work for live detections.
