### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file while pip install face_recognition

### ISSUE THREAD

**Issue by vagdevik** [ageitgey/face_recognition#1256]
* face_recognition version: 1.2.3
* Python version: 3.6.8
* Operating System: Ubuntu

### Description

I was simply trying to install face_recognition module, and tried through all these commands:

```
pip install face_recognition==1.2.3
pip install face_recognition
pip3 install face_recognition==1.2.3
pip3 install face_recognition

```
All of them have given the below error:

```
Collecting face_recognition==1.2.3
  Using cached face_recognition-1.2.3-py2.py3-none-any.whl (21 kB)
Collecting Click>=6.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting dlib>=19.7
  Using cached dlib-19.21.1.tar.gz (3.6 MB)
Collecting face-recognition-models>=0.3.0
  Using cached face_recognition_models-0.3.0-py2.py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 339, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 172, in get_dependencies
    for r in candidate.iter_dependencies(with_requires)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 171, in <listcomp>
    r
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 257, in iter_dependencies
    requires = self.dist.requires() if with_requires else ()
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 319, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 524, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 89, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/home/vagdevik/venv/lib/python3.6/site-packages/pip/_internal/distributions/wheel.py", line 30, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/usr/local/anaconda/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/local/anaconda/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by vagdevik** [comment]
This issue was fixed upon clearing the pip cache using the below command:

```
rm -rf ~/.cache/pip
```
