### ISSUE TITLE
dll load failure

### ISSUE THREAD

**Issue by natalius** [ageitgey/face_recognition#1275]
* face_recognition version: latest version
* Python version: 3.9
* Operating System: Windows 10 Pro

Basically I have run successfully on face recognition webcam on my environment (windows 10). And I want to run another examples and I have the following error:  

I already installed scikit-learn successfully

C:\Users\Asus\AppData\Local\Programs\Python\Python39>python face_recognition_knn.py
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\face_recognition_knn.py", line 35, in <module>
    from sklearn import neighbors
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from .base import clone
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py", line 25, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    import scipy.stats
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\__init__.py", line 391, in <module>
    from .stats import *
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\stats\stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\spatial\__init__.py", line 98, in <module>
    from .qhull import *
ImportError: DLL load failed while importing qhull: The specified module could not be found.

Anyone can help ? Thanks a lot

```

**Comment by omerasif57** [comment]
How are you setting up your python environment (virtual or System?). Looks like you are using System Python. 
To make it simple troubleshooting the problem, you can try creating a virtual one and then run `.py` scripts.

[Try Step-5 from here](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-windows-10)

1. Create a virtual env following above link
2. Activate it
3. Then within face_recognition (cloned repository folder) do: for example
$ (virtualenv) c:\code\face_recognition>   `pip install -r requirements.txt`

After installation, try running a script. Good Luck!
