### ISSUE TITLE
Cannot compile Dlib with CUDA

### ISSUE THREAD

**Issue by SheldonPatnett** [ageitgey/face_recognition#1291]
* face_recognition version: v1.1.2
* Python version: 3.8
* Operating System: Windows 10

### Description

Trying to compile dlib-19.21 with CUDA. Have tried with just ```python setup.py install``` and receiving the same traceback.

### What I Did

```
PS C:\Users\root\Downloads\dlib-19.21> python setup.py install --set DLIB_USE_CUDA=1
C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
running install
running bdist_egg
running egg_info
writing tools/python\dlib.egg-info\PKG-INFO
writing dependency_links to tools/python\dlib.egg-info\dependency_links.txt
writing top-level names to tools/python\dlib.egg-info\top_level.txt
package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
reading manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools\python\build*'
writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Users\root\Downloads\dlib-19.21\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\root\Downloads\dlib-19.21\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=C:\Users\root\AppData\Local\Programs\Python\Python39\python.exe -DDLIB_USE_CUDA=1 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\root\Downloads\dlib-19.21\build\lib.win-amd64-3.9 -A x64'
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/root/AppData/Local/Programs/Python/Python39/python.exe (found version "3.9")
-- Found PythonLibs: C:/Users/root/AppData/Local/Programs/Python/Python39/libs/Python39.lib
-- pybind11 v2.2.2
-- Using CMake version: 3.18.4
-- Compiling dlib version: 19.21.0
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Enabling AVX instructions
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2 (found suitable version "11.2", minimum required is "7.5")
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/lib/x64/cudnn.lib
-- Building a CUDA test project to see if your compiler is compatible with CUDA...
-- Building a cuDNN test project to check if you have the right version of cuDNN installed...
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/root/Downloads/dlib-19.21/build/temp.win-amd64-3.9/Release
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
  cuda_dlib.cu
CUSTOMBUILD : nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures a
re deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning). [C:\Users\
root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]
C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1497): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear") is not allowed [C:\Users\root\Downloads\dlib-19.21\build\temp
.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1497): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1502): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear") is not allowed [C:\Users\root\Downloads\dlib-19.21\build\temp
.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1502): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1534): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_strided") is not allowed [C:\Users\root\Downloads\dlib-19.21\bu
ild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1534): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1539): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_strided") is not allowed [C:\Users\root\Downloads\dlib-19.21\bu
ild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1539): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1608): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient") is not allowed [C:\Users\root\Downloads\dlib-19.21\b
uild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1608): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1613): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient") is not allowed [C:\Users\root\Downloads\dlib-19.21\b
uild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1613): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1644): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient_strided") is not allowed [C:\Users\root\Downloads\dlib
-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1644): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1649): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient_strided") is not allowed [C:\Users\root\Downloads\dlib
-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1649): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

  16 errors detected in the compilation of "C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu".
CUSTOMBUILD : nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures a
re deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning). [C:\Users\
root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]
  cuda_dlib.cu
  CMake Error at dlib_generated_cuda_dlib.cu.obj.Release.cmake:280 (message):
    Error generating file
    C:/Users/root/Downloads/dlib-19.21/build/temp.win-amd64-3.9/Release/dlib_build/CMakeFiles/dlib.dir/cuda/Release/dli
  b_generated_cuda_dlib.cu.obj


C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240
,5): error MSB8066: Custom build for 'C:\Users\root\Downloads\dlib-19.21\dlib\cuda\cuda_dlib.cu;C:\Users\root\Downloads
\dlib-19.21\dlib\cuda\cusolver_dlibapi.cu' exited with code 1. [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64
-3.9\Release\dlib_build\dlib.vcxproj]
Traceback (most recent call last):
  File "C:\Users\root\Downloads\dlib-19.21\setup.py", line 223, in <module>
    setup(
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\Downloads\dlib-19.21\setup.py", line 135, in run
    self.build_extension(ext)
  File "C:\Users\root\Downloads\dlib-19.21\setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
PS C:\Users\root\Downloads\dlib-19.21> python setup.py install --set DLIB_USE_CUDA=1 --set USE_AVX_INSTRUCTIONS=1 --set CUDA_NVCC_FLAGS="--expt-relaxed-constexpr"
C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
running install
running bdist_egg
running egg_info
writing tools/python\dlib.egg-info\PKG-INFO
writing dependency_links to tools/python\dlib.egg-info\dependency_links.txt
writing top-level names to tools/python\dlib.egg-info\top_level.txt
package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
reading manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools\python\build*'
writing manifest file 'tools/python\dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
Invoking CMake setup: 'cmake C:\Users\root\Downloads\dlib-19.21\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\root\Downloads\dlib-19.21\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=C:\Users\root\AppData\Local\Programs\Python\Python39\python.exe -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1 -DCUDA_NVCC_FLAGS=--expt-relaxed-constexpr -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\root\Downloads\dlib-19.21\build\lib.win-amd64-3.9 -A x64'
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- pybind11 v2.2.2
-- Using CMake version: 3.18.4
-- Compiling dlib version: 19.21.0
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Looking for cuDNN install...
-- Found cuDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/lib/x64/cudnn.lib
-- Enabling CUDA support for dlib.  DLIB WILL USE CUDA
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/root/Downloads/dlib-19.21/build/temp.win-amd64-3.9/Release
Invoking CMake build: 'cmake --build . --config Release -- /m'
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building NVCC (Device) object dlib_build/CMakeFiles/dlib.dir/cuda/Release/dlib_generated_cuda_dlib.cu.obj
  cuda_dlib.cu
CUSTOMBUILD : nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures a
re deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning). [C:\Users\
root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]
C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1497): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear") is not allowed [C:\Users\root\Downloads\dlib-19.21\build\temp
.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1497): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1502): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear") is not allowed [C:\Users\root\Downloads\dlib-19.21\build\temp
.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1502): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1534): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_strided") is not allowed [C:\Users\root\Downloads\dlib-19.21\bu
ild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1534): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1539): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_strided") is not allowed [C:\Users\root\Downloads\dlib-19.21\bu
ild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1539): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1608): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient") is not allowed [C:\Users\root\Downloads\dlib-19.21\b
uild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1608): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1613): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient") is not allowed [C:\Users\root\Downloads\dlib-19.21\b
uild\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1613): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1644): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient_strided") is not allowed [C:\Users\root\Downloads\dlib
-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1644): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1649): error : calling a __host__ function("__floorf") from a
 __global__ function("dlib::cuda::_cuda_resize_bilinear_gradient_strided") is not allowed [C:\Users\root\Downloads\dlib
-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu(1649): error : identifier "__floorf" is undefined in device c
ode [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]

  16 errors detected in the compilation of "C:/Users/root/Downloads/dlib-19.21/dlib/cuda/cuda_dlib.cu".
CUSTOMBUILD : nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures a
re deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning). [C:\Users\
root\Downloads\dlib-19.21\build\temp.win-amd64-3.9\Release\dlib_build\dlib.vcxproj]
  cuda_dlib.cu
  CMake Error at dlib_generated_cuda_dlib.cu.obj.Release.cmake:280 (message):
    Error generating file
    C:/Users/root/Downloads/dlib-19.21/build/temp.win-amd64-3.9/Release/dlib_build/CMakeFiles/dlib.dir/cuda/Release/dli
  b_generated_cuda_dlib.cu.obj


C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240
,5): error MSB8066: Custom build for 'C:\Users\root\Downloads\dlib-19.21\dlib\cuda\cuda_dlib.cu;C:\Users\root\Downloads
\dlib-19.21\dlib\cuda\cusolver_dlibapi.cu' exited with code 1. [C:\Users\root\Downloads\dlib-19.21\build\temp.win-amd64
-3.9\Release\dlib_build\dlib.vcxproj]
Traceback (most recent call last):
  File "C:\Users\root\Downloads\dlib-19.21\setup.py", line 223, in <module>
    setup(
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\root\Downloads\dlib-19.21\setup.py", line 135, in run
    self.build_extension(ext)
  File "C:\Users\root\Downloads\dlib-19.21\setup.py", line 175, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "C:\Users\root\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
```

**Comment by SheldonPatnett** [comment]
Build mixup, please delete this issue to avoid confusion

**Comment by gaurav7700** [comment]
> Build mixup, please delete this issue to avoid confusion

Can you please help me, i am getting the same issue

**Comment by SheldonPatnett** [comment]
@gaurav7700 Sorry for the late reply. You could be having a similar issue but there could be numerous unique factors such as OS, Dlib version, compiler, and more which are unique to your issue. Please create an issue providing these details, we will try to help.
