### ISSUE TITLE
cudaMalloc out of memory with model=cnn, only when processing directory

### ISSUE THREAD

**Issue by sandeen** [ageitgey/face_recognition#1414]
* face_recognition version: 1.2.3
* Python version: 3.9.7
* Operating System: Fedora 33, with cuda-enabled dlib 19.23, locally built

### Description

I am trying to process multiple jpg images in a directory using the face_detection cli and running out of GPU memory.
Processing the same images one at a time works fine.

### What I Did

```
# face_detection --model=cnn .
Traceback (most recent call last):
  File "/usr/local/bin/face_detection", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/face_recognition/face_detection_cli.py", line 71, in main
    test_image("b.jpg", model)
  File "/usr/local/lib/python3.9/site-packages/face_recognition/face_detection_cli.py", line 19, in test_image
    face_locations = face_recognition.face_locations(unknown_image, number_of_times_to_upsample=0, model=model)
  File "/usr/local/lib/python3.9/site-packages/face_recognition/api.py", line 119, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "/usr/local/lib/python3.9/site-packages/face_recognition/api.py", line 103, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
RuntimeError: Error while calling cudaMalloc(&data, n) in file /root/rpmbuild/BUILD/dlib-19.23/dlib/cuda/cuda_data_ptr.cpp:58. code: 2, reason: out of memory
```
Testing the images one at a time works fine (no faces are found):
```
# ls -l
total 456
-rw-r--r--. 1 root root 287287 Mar  4 13:53 a.jpg
-rw-r--r--. 1 root root 174551 Mar  4 13:53 b.jpg
# file *.jpg
a.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 2048x2048, components 3
b.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=1], baseline, precision 8, 1242x1243, components 3

# face_detection --model=cnn a.jpg
# face_detection --model=cnn b.jpg
#
```
If I modify face_detection_cli.py to simply call test_image() twice:
```
    test_image("a.jpg", model)
    test_image("b.jpg", model)
```

I get the same failure. How does the package (or dlib?) decide how to load up the GPU?

GPU details:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 470.74       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 35%   26C    P0    N/A /  30W |      0MiB /  2000MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by sandeen** [comment]
Perhaps this is a dlib behavior. https://github.com/davisking/dlib/issues/2537

**Comment by sandeen** [comment]
There seems to be some hysteresis ... even though each image fits individually, testing them in series fails. I've hacked something up to downsample and try again if I get an out of memory error.
