### ISSUE TITLE
Unable to open ./shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by Sherif-Sakran** [ageitgey/face_recognition#1435]
* Python version: 3.10
* Operating System: windows 10

I am trying to get an executable file for my project through pyinstaller, but I am facing an error regarding the following model: shape_predictor_68_face_landmarks.dat

Here is the error message I get:

Traceback (most recent call last):
  File "tag2.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "face_recognition\__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 493, in exec_module
  File "face_recognition\api.py", line 20, in <module>
RuntimeError: Unable to open C:\Users\Sherif\AppData\Local\Temp\\_MEI202682\face_recognition_models\models\shape_predictor_68_face_landmarks.dat

Could anyone help please?

**Comment by fafamendes** [comment]
+1
