### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by riddhiman1** [ageitgey/face_recognition#1437]
* face_recognition version: 1.3.0
* Python version:  3.10.5
* Operating System: Edition	Windows 11 Home Single Language
                                 Version	21H2
                                 OS build	22000.832

### Description

I am just trying to run a simple image recognition program

### What I Did

`import cv2
import numpy as np
import face_recognition

imge_given = face_recognition.load_image_file("elon.jpg")
imge_given = cv2.cvtColor(imge_given,cv2.COLOR_BGR2RGB)
#----------Finding face Location for drawing bounding boxes-------
face = face_recognition.face_location(imge_given)[0]
copy = imge_given.copy()
#-------------------Drawing the Rectangle-------------------------
cv2.rectangle(copy, (face[3], face[0]),(face[1], face[2]), (255,0,255), 2)
cv2.imshow('copy', copy)
cv2.imshow('elon',imge_given)
cv2.waitKey(0)

train_encode = face_recognition.face_encodings(imge_given)[0]

#----------------------- lets test an image--------------------#
test = face_recognition.load_image_file("elon_2.jpg")
test = cv2.cvtColor(test, cv2.COLOR_BGR2RGB)
test_encode = face_recognition.face_encodings(test)[0]
print(face_recognition.compare_faces([train_encode],test_encode)) # Result == True / False`

OUTPUT:
 python .\face_match.py
Traceback (most recent call last):
  File "D:\PythonProject\face_match.py", line 3, in <module>
    import face_recognition
  File "D:\PythonProject\face_recognition.py", line 191
    df = pd.read_csv("UserDetails\UserDetails.csv")
                                                                             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 11-12: truncated \UXXXXXXXX escape

**Comment by riddhiman1** [comment]
Hello I had to just rename some files.
