### ISSUE TITLE
Cannot install dlib on server

### ISSUE THREAD

**Issue by abedputra** [ageitgey/face_recognition#1494]
* face_recognition version: -
* Python version: 3.9.16
* Operating System: Linux

### Description

1. I try to install `cmake` and successes
2. Install `dlib` and show error message and cannot install it on my server

```
Collecting dlib==19.22
  Using cached dlib-19.22.0.tar.gz (7.4 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'tools/python/dlib/__init__.py' not found (or not a regular file)
      running build_ext
      Building extension for Python 3.9.16 (main, Feb  6 2023, 23:24:10)
      Invoking CMake setup: 'cmake /tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/build/lib.linux-x86_64-3.9 -DPYTHON_EXECUTABLE=/home/connectw/virtualenv/face_recognition/3.9/bin/python3.9_bin -DCMAKE_BUILD_TYPE=Release'
      -- The C compiler identification is unknown
      -- The CXX compiler identification is unknown
      CMake Error at CMakeLists.txt:14 (project):
        No CMAKE_C_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
        the compiler, or to the compiler name if it is in the PATH.
      
      
      CMake Error at CMakeLists.txt:14 (project):
        No CMAKE_CXX_COMPILER could be found.
      
        Tell CMake where to find the compiler by setting either the environment
        variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
        to the compiler, or to the compiler name if it is in the PATH.
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/setup.py", line 222, in <module>
          setup(
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/connectw/virtualenv/face_recognition/3.9/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/setup.py", line 134, in run
          self.build_extension(ext)
        File "/tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/setup.py", line 171, in build_extension
          subprocess.check_call(cmake_setup, cwd=build_folder)
        File "/opt/alt/python39/lib64/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-1082tbk4/dlib_3f6935c24cfe47dd9dc81a2ab682518a/build/lib.linux-x86_64-3.9', '-DPYTHON_EXECUTABLE=/home/connectw/virtualenv/face_recognition/3.9/bin/python3.9_bin', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
```

### What I Did

```
I tried downloading the dlib and manual installing, installing from GitHub live source, or typing `pip install dlib==19.22` but all failed.
```

**Comment by BirenMer** [comment]
Hey is your OS Ubuntu ??

**Comment by abedputra** [comment]
No its Centos 7. But I already resolve it. Thanks..

**Comment by ChinmoyPadhi** [comment]
> No its Centos 7. But I already resolve it. Thanks..

How??? could you please comment

**Comment by abedputra** [comment]
Try to follow this website
https://learnopencv.com/install-dlib-on-ubuntu/

on that website they use Ubuntu.

Thanks
