### ISSUE TITLE
Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x1046d73f0>, array([[[ 8,  4,  1], error

### ISSUE THREAD

**Issue by sxtj** [ageitgey/face_recognition#1516]
* face_recognition version: to tired to check
* Python version: 3.11
* Operating System:OSX vENTURA 13.0

### Description

I made my own implementation of the face_recognition example code of detecting faces from a video. For a little bit it would stop after 4 frames, then I realized that the video had an intro. But now I am trying to run the facerec_video_file.py example and it is throwing me this long error. I am using the exact same file names and the exact same code. 

The error below is what I get. Sorry if something doesnt make sense, its late at night and im tired. 

### What I Did

```
Traceback (most recent call last):
  File "/Users/main/Desktop/face/main.py", line 52, in <module>
    face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/main/Desktop/face/lib/python3.11/site-packages/face_recognition/api.py", line 214, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/main/Desktop/face/lib/python3.11/site-packages/face_recognition/api.py", line 214, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], num_jitters: int = 0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], batch_faces: List[_dlib_pybind11.full_object_detections], num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], num_jitters: int = 0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x1046d73f0>, array([[[ 8,  4,  1],
        [11,  8,  4],
        [17, 13, 10],
        ...,
        [24,  9,  1],
        [24,  9,  1],
        [24,  9,  1]],

       [[ 8,  4,  1],
        [11,  8,  4],
        [17, 13, 10],
        ...,
        [24,  9,  1],
        [24,  9,  1],
        [24,  9,  1]],

       [[ 6,  3,  0],
        [10,  6,  3],
        [16, 12,  9],
        ...,
        [24,  9,  1],
        [24,  9,  1],
        [24,  9,  1]],

       ...,

       [[ 6,  3,  0],
        [ 6,  3,  0],
        [ 9,  3,  0],
        ...,
        [17,  2,  0],
        [10,  2,  3],
        [10,  2,  3]],

       [[ 6,  3,  0],
        [ 6,  3,  0],
        [ 9,  3,  0],
        ...,
        [17,  2,  0],
        [10,  2,  1],
        [10,  2,  1]],

       [[ 6,  3,  0],
        [ 6,  3,  0],
        [ 9,  3,  0],
        ...,
        [17,  2,  0],
        [10,  2,  1],
        [10,  2,  1]]], dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x104ac5070>, 1
```

**Comment by sxtj** [comment]
the solution for me was changing rgb_frame = frame[:, :, ::-1] to rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
