### ISSUE TITLE
image_recognition:  Error while calling cudaGetDevice

### ISSUE THREAD

**Issue by nys87** [ageitgey/face_recognition#1519]
* face_recognition version:
`face-recognition  1.3.0`

* Dlib:
`dlib 9.24.2`

* Test dlib:
`python3 -c "import dlib; print(dlib.DLIB_USE_CUDA); print (dlib.cuda.get_num_devices())"`
```
True
1
```

* nvidia-smi:
```
Sun Jul  9 13:40:33 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050        Off | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8              N/A / ERR! |      2MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

* Python version:
`Python 3.10.6`

* Operating System:
`Ubuntu 22.04.2 LTS`

### Description
Hello,
sorry for my English
I try to recognize faces in photos using my GPU, when building dlib without GPU support **everything works fine**,
but when trying to use dlib with my GPU I always getting the error(error text below).
### What I Did

* Here is a **simplified** code example that does not work:
```
#!/usr/bin/env python3

import multiprocessing
import face_recognition
import time

def image_recognition(imagePath):
    result = {}
    faces_hashes = []

    img = face_recognition.load_image_file(imagePath)
    faces = face_recognition.face_encodings(img)

    if faces:
        for f in faces:
            faces_hashes.append(f)

        result['faces_hashes'] = faces_hashes
        return result

    else:
        return result

class FaceDetectThread(multiprocessing.Process):
    def __init__(self, name, i):
        super().__init__()
        self.steam_id = i

    def run(self):
        image_recognition("test_3.jpg")
        print('i: ', self.steam_id)

def main():
    for i in range(0, 10000):
        while True:
            if len(multiprocessing.active_children()) - 1 <= 10:
                thread = FaceDetectThread('Thread-' + str(i), i)
                thread.start()
                break

            else:
                time.sleep(2)

if __name__ == "__main__":
    main()
```

* Error:
`RuntimeError: Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-install-7cxxh58v/dlib_92209fb4d4c54bb99153cc36eef5c862/dlib/cuda/gpu_data.cpp:204. code: 3, reason: initialization error
Process FaceDetectThread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/tester/Parsers/parser_steam/./test_gpu.py", line 33, in run
    image_recognition("test_3.jpg")
  File "/home/tester/Parsers/parser_steam/./test_gpu.py", line 14, in image_recognition
    faces = face_recognition.face_encodings(img)
  File "/usr/local/lib/python3.10/dist-packages/face_recognition/api.py", line 214, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
  File "/usr/local/lib/python3.10/dist-packages/face_recognition/api.py", line 214, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
`

**PS: I will be very grateful for any advice, I will provide any information as quickly as possible.**

**Comment by wenxuezhang** [comment]
I encountered the same problem, waiting for experts to answer
