### ISSUE TITLE
Import Error: libjpeg.so.62: version `LIBJPEGTURBO_6.2' not found

### ISSUE THREAD

**Issue by MuXiaoYun** [ageitgey/face_recognition#1520]
### Description

while running the example code, i came up with:

```
root@ubuntu:/usr# python3 recog.py                                          
Traceback (most recent call last):
  File "recog.py", line 1, in <module>
    import face_recognition
  File "/usr/local/python3/lib/python3.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/local/python3/lib/python3.7/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/usr/local/python3/lib/python3.7/site-packages/dlib/__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: /usr/lib/arm-linux-gnueabihf/libjpeg.so.62: version `LIBJPEGTURBO_6.2' not found (required by /usr/local/python3/lib/python3.7/site-packages/_dlib_pybind11.cpython-37m-arm-linux-gnueabihf.so)
```

**Comment by MuXiaoYun** [comment]
Using an older version of dlib will do.
My former version is 19.24.2
Just change it into 19.8.2
