### ISSUE TITLE
dlib

### ISSUE THREAD

**Issue by caigang2501** [ageitgey/face_recognition#1559]
* face_recognition version:
* Python version:
* Operating System:

### Description

run the program,and tell me can't find dlib.
so,i run the commond pip install dlib,but installed failed

### What I Did
pip install dlib
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      running bdist_wheel
      running build
      running build_ext
      <string>:125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

**Comment by KiLJ4EdeN** [comment]
> * face_recognition version:
> 
>     * Python version:
> 
>     * Operating System:
> 
> 
> ### Description
> 
> run the program,and tell me can't find dlib. so,i run the commond pip install dlib,but installed failed
> ### What I Did
> 
> pip install dlib
> 
> ```
> Paste the command(s) you ran and the output.
> If there was a crash, please include the traceback here.
> ```
> 
> Building wheels for collected packages: dlib Building wheel for dlib (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Building wheel for dlib (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [78 lines of output] running bdist_wheel running build running build_ext :125: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

Check and see if you have a cxx compiler and cmake on your computer, since dlib must be compiled.

**Comment by Shabeena-18** [comment]
PS C:\Users\SHAIK  SHABEENA> pip install cmake
Requirement already satisfied: cmake in c:\users\shaik  shabeena\appdata\local\programs\python\python311\lib\site-packages (3.29.2)
PS C:\Users\SHAIK  SHABEENA>
PS C:\Users\SHAIK  SHABEENA> pip install dlib
Collecting dlib
  Using cached dlib-19.24.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\SHAIK  SHABEENA\AppData\Local\Programs\Python\Python311\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'

      ERROR: CMake must be installed to build dlib

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects
PS C:\Users\SHAIK  SHABEENA>




i am getting this error how to fix this could you please help me in this regard its very urgent

**Comment by jsjg-8** [comment]
Simply download the whl file and install it manually
