### ISSUE TITLE
ModuleNotFoundError: No module named 'face_recognition'

### ISSUE THREAD

**Issue by Victorvikson1996** [ageitgey/face_recognition#1564]
* face_recognition version:f ace-recognition 1.3.0
* Python version:python 3.8 
* Operating System: MacOS M1

### Description

Traceback (most recent call last):
  File "/Users/chukwuebuka/web/project2/backend/my_flask.py", line 3, in <module>
    from face import recognize_faces
  File "/Users/chukwuebuka/web/project2/backend/face.py", line 1, in <module>
    import face_recognition
ModuleNotFoundError: No module named 'face_recognition'

### What I Did
trying to run a python code where i used the face regonition library but I get this errors 
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by HeatleesFlame** [comment]
Did you installed library by the pip?

**Comment by Mr-Dark-debug** [comment]
give me the commands that you ran.

**Comment by facundo-cachan** [comment]
I removed .venv, install again, execute` pip3 install --upgrade setuptools`, and fix the issue.

**Comment by Mr-Dark-debug** [comment]
Ok
