### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by isline** [ageitgey/face_recognition#205]
* face_recognition version:1.00
* Python version:3.6
* Operating System:Win7
dlib version：19.7
### Description
Python Report Error：
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/untitled1/FaceRecognition/1.py", line 12, in <module>
    biden_face_encoding = face_recognition.face_encodings(biden_image)[0]
  File "D:\Program Files\Python36\lib\site-packages\face_recognition\api.py", line 189, in face_encodings
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations)
  File "D:\Program Files\Python36\lib\site-packages\face_recognition\api.py", line 148, in _raw_face_landmarks
    face_locations = _raw_face_locations(face_image)
  File "D:\Program Files\Python36\lib\site-packages\face_recognition\api.py", line 97, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
TypeError: 'NoneType' object is not callable

 Function of “face_detector” in api.py is following：
return face_detector(img, number_of_times_to_upsample)
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by mubarisct** [comment]
well done my bwoy
