### ISSUE TITLE
dlib's problem with libjpeg

### ISSUE THREAD

**Issue by gpp8p** [ageitgey/face_recognition#216]
Python - 3.5
Ubuntu 17.04

I have face-recognition working in docker, but I'd like to run the latest version outside of that.  After what appears to be a successful install, I get the following when I attempt to run it:

gpp8p@woozel:/media/gpp8p/ExtraDrive1/frecog_1028/face_recognition$ python3 ./examples/recognize_faces_in_pictures.py
Traceback (most recent call last):
  File "./examples/recognize_faces_in_pictures.py", line 1, in <module>
    import face_recognition
  File "/home/gpp8p/.local/lib/python3.5/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/gpp8p/.local/lib/python3.5/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/home/gpp8p/.local/lib/python3.5/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory

Checking my libraries, I notice that I have libjpeg.so.8
gpp8p@woozel:/media/gpp8p/ExtraDrive1/frecog_1028/face_recognition$ ldconfig -p | grep -i libjp
	libjpeg.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so.8

Is this a Ubuntu 17.04 issue that might be resolved by upgrading to 17.10, or is there a way I can upgrade this specific library only ?

-George Pipkin
Afton, Va.

**Comment by Wisgon** [comment]
My system is ubuntu17.10 and I didn't get this problem, I installed successfully.

**Comment by santosh-burada** [comment]
**I got the same issue while running my docker image**
![Screenshot (166)](https://user-images.githubusercontent.com/55043057/119312713-53ab9b80-bc90-11eb-8f90-c5ac65594beb.png)
