### ISSUE TITLE
Issue for resize of fram

### ISSUE THREAD

**Issue by vinayentc** [ageitgey/face_recognition#270]
* face_recognition version:
* Python version: 3
* Operating System: Windows

### Description
Hello,

I get below error -

runfile('C:/Python/somecode.py', wdir='C:/Python')
Traceback (most recent call last):

  File "<ipython-input-7-b62a5e52865c>", line 1, in <module>
    runfile('C:/Python/somecode.py', wdir='C:/Python')

  File "C:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Python/somecode.py", line 45, in <module>
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

error: C:\bld\opencv_1510966172919\work\opencv-3.3.0\modules\imgproc\src\imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

Can you please help.

Thanks..!!

**Comment by yosemite1998** [comment]
Sometimes, no frame was read from the stream. As a result, you have to add if statement to handle it. you could use return status of resize() to determine whether there is a frame or not. If no frame, just continue and jump to the next iteration.
