### ISSUE TITLE
Script crashes when no face is found in an image

### ISSUE THREAD

**Issue by woutervdijke** [ageitgey/face_recognition#34]
* face_recognition version: 0.1.10
* Python version: 3.6.0
* Operating System: macOS 10.12

### Description

I tried to run face_recognition from the command line. The known faces input was a folder containing 4 jgg files, the unknown faces input was a folder containing 2 jpg files. On one of the known files, no face was detected. This caused the program to crash. When I remove the offending file (where no face was found), the program runs perfectly and returns a result for the two unknown faces.

### What I Did

```
mbp-van-wouter:kface wouter$ face_recognition /Users/wouter/Desktop/kface/known /Users/wouter/Desktop/kface/unknown
WARNING: No faces found in /Users/wouter/Desktop/kface/known/wouter.jpg. Ignoring file.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/face_recognition", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition/cli.py", line 61, in main
    known_names, known_face_encodings = scan_known_people(known_people_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition/cli.py", line 27, in scan_known_people
    known_face_encodings.append(encodings[0])
IndexError: list index out of range
```

**Comment by ageitgey** [comment]
Thanks! I'll fix it.

**Comment by ageitgey** [comment]
Give version 1.11 a shot. Thanks!

**Comment by woutervdijke** [comment]
That was quick! It works perfectly now. Thank you!

**Comment by ageitgey** [comment]
No problem. Thanks for pointing out the bug. I had just missed an "else" in the original code :)
