### ISSUE TITLE
Runtime err : Expected numpy.ndarray of uint8 

### ISSUE THREAD

**Issue by Peppuz** [ageitgey/face_recognition#386]
* face_recognition version: 1.2.1
* Python version: 2.7
* Operating System: macOS 10.12.1

### Description
The code throws a Runtime error when face_detector is called, printing: 
```Expected numpy.ndarray of uint8```

### What I Did

```
import face_recognition
image = face_recognition.load_image_file("your_file.jpg")
face_locations = face_recognition.face_locations(image)
```
## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/face_recognition/api.py", line 116, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, model)]
  File "/Library/Python/2.7/site-packages/face_recognition/api.py", line 100, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
RuntimeError: Expected numpy.ndarray of uint8
```

**Comment by ageitgey** [comment]
Your code looks file. Would it be possible the share the image file that gave you this error?

**Comment by GoodBoyth** [comment]
I got this problem too.  
I check out my images , the reason for this exception is my images were damaged.
