### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by konstantin42127** [ageitgey/face_recognition#392]
* face_recognition version: the last
* Python version: 3.6
* Operating System: windows 10 x64 system language - russian

### Description

I tried to install via pip and got this error:
```
Exception:
Traceback (most recent call last):
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 32: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\lik47\appdata\local\programs\python\python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 32: invalid continuation byte
```

### What I Did

```
pip install face_recognition
```

**Comment by ageitgey** [comment]
That looks more like a problem with your python installation than with this library. Are you able to pip install any other library?

**Comment by donaldxu** [comment]
update your pip
