### ISSUE TITLE
ModuleNotFoundError: No module named 'face_recognition.face_recognition_cli

### ISSUE THREAD

**Issue by lgertel** [ageitgey/face_recognition#407]
* face_recognition version: Latest
* Python version: 3.6.3
* Operating System: MacOS

### Description

Can't run the KNN example! Everything else is working fine!

### What I Did

```
$ python knn.py
Traceback (most recent call last):
  File "knn.py", line 30, in <module>
    from face_recognition.face_recognition_cli import image_files_in_folder
ModuleNotFoundError: No module named 'face_recognition.face_recognition_cli'
```

**Comment by ageitgey** [comment]
The example code in git is newer than what you have installed from pip (because it's under development). 

To make the example code in git work with the latest released version of the library, just change:

```python
from face_recognition.face_recognition_cli import image_files_in_folder
```

to:

```python
from face_recognition.cli import image_files_in_folder
```

**Comment by lgertel** [comment]
Great! Have copied from the source and worked too!
ty

**Comment by MastroGeppetto14** [comment]
File "proveface.py", line 1, in <module>
    from face_recognition_cli import image_files_in_folder, load_image_file, face_encodings, compare_faces
ImportError: No module named face_recognition_cli

**Comment by canssd** [comment]
same problem
