### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Sega01** [ageitgey/face_recognition#418]
* face_recognition version: latest
* Python version: 3.6
* Operating System: Debian Stretch

### Description

I took the dockerfile and tried to install the repo on my Raspberry Pi 3, but i alwas get an error because of ModuleNotFoundError: No module named 'numpy' at setup.py.

### What I Did

Downloaded the repo files and tried to install throught the dockerfile: 
https://github.com/ageitgey/face_recognition/blob/master/Dockerfile

```
Running setup.py bdist_wheel for scipy: finished with status 'error'
[main]    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1lmk6ekg/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpndaspagjpip-wheel- --python-tag cp36:
[main]    Traceback (most recent call last):
[main]      File "<string>", line 1, in <module>
[main]      File "/tmp/pip-build-1lmk6ekg/scipy/setup.py", line 418, in <module>
[main]        setup_package()
[main]      File "/tmp/pip-build-1lmk6ekg/scipy/setup.py", line 398, in setup_package
[main]        from numpy.distutils.core import setup
[main]    ModuleNotFoundError: No module named 'numpy'
[main]    ----------------------------------------
[main]    Failed building wheel for scipy
[main]  
[main]    Running setup.py clean for scipy
[main]    Complete output from command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1lmk6ekg/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
[main]    `setup.py clean` is not supported, use one of the following instead:
[main]      - `git clean -xdf` (cleans all files)
[main]      - `git clean -Xdf` (cleans all versioned files, doesn't touch
[main]                          files that aren't checked into the git repo)
[main]    Add `--force` to your command to use it anyway if you must (unsupported).
[main]    ----------------------------------------
[main]    Failed cleaning build dir for scipy
[main]  
[main]  Successfully built face-recognition-models numpy Pillow
[main]  Failed to build scipy
[main]  Installing collected packages: face-recognition-models, Click, numpy, Pillow, scipy
[main]    Running setup.py install for scipy: started

```

**Comment by ageitgey** [comment]
Can you share the exact commands you ran?

**Comment by RishabGargeya** [comment]
@Sega01 Seeing the same error on Raspberry Pi 2.0. Did you find a fix?
