### ISSUE TITLE
Cannot import face_recognition

### ISSUE THREAD

**Issue by creativeishu** [ageitgey/face_recognition#44]
* face_recognition version: 0.1.11
* Python version: 2.7.13
* Operating System: Ubuntu 16.04

### Description

Everything installed properly, but I am not able to ```import face_recognition``` into my python.

### What I Did

```
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces
  File "/opt/conda/lib/python2.7/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/opt/conda/lib/python2.7/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /opt/conda/lib/python2.7/site-packages/dlib/dlib.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```

**Comment by ageitgey** [comment]
That sounds like you have a version mismatch with the version of gcc used to compile everything. I honestly haven't seen anything like that happen before with Ubuntu 16.04. But I also don't use Anaconda, so I'm guessing it's related to that? I'm not really sure.

**Comment by creativeishu** [comment]
Actually, I am running this on a docker image that I configured using following Dockerfile:

```
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install wget -y

FROM continuumio/anaconda:latest
RUN apt-get install python-pip python-dev -y
RUN pip install --upgrade pip

RUN pip install theano tensorflow keras
RUN pip install fasttext

RUN apt-get install build-essential cmake pkg-config libgtk2.0-dev python-tk -y
RUN pip install opencv-python

RUN apt-get install nano vim -y

RUN conda install -c menpo dlib=18.18
RUN pip install face_recognition
```
Do you see any package I am missing here?

**Comment by creativeishu** [comment]
I re-tried building with the following docker file:

```
FROM ubuntu:latest
RUN apt-get update
RUN apt-get install wget -y

FROM continuumio/anaconda:latest
RUN apt-get install python-pip python-dev -y
RUN pip install --upgrade pip

RUN pip install theano tensorflow keras
RUN pip install fasttext

RUN apt-get install build-essential cmake pkg-config libgtk2.0-dev python-tk -y
RUN pip install opencv-python

RUN apt-get install nano vim -y

RUN apt-get install libboost-all-dev -y
RUN pip install dlib
RUN pip install face_recognition
```
This time it installed ```dlib``` version 19.4.0. But this didn't solve the problem. I am still getting the same error. 

```
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces
  File "/opt/conda/lib/python2.7/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/opt/conda/lib/python2.7/site-packages/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: /opt/conda/lib/python2.7/site-packages/dlib/dlib.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz
```

**Comment by ageitgey** [comment]
It seems related to how the Anaconda packages where build. I'm not very familiar with Anaconda, so I don't really know for sure.

Did you try the Dockerfile in this repo? Did that one work for you?
