### ISSUE TITLE
Unable to run python setup.py install --yes USE_AVX_INSTRUCTIONS --yes 

### ISSUE THREAD

**Issue by Saini-96** [ageitgey/face_recognition#456]
* face_recognition version:
* Python version:
* Operating System:

### Description
For installing face_recognition, I installed Visual studio with C++, boost and did as mentioned but at last while running python setup.py install --yes USE_AVX_INSTRUCTIONS --yes  in cmd getting error

C:\Users\hp 1\dlib\dlib-master>python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA
running install
running bdist_egg
running egg_info
writing dlib.egg-info\PKG-INFO
writing top-level names to dlib.egg-info\top_level.txt
writing dependency_links to dlib.egg-info\dependency_links.txt
package init file 'dlib\__init__.py' not found (or not a regular file)
reading manifest file 'dlib.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dlib.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Fatal error in launcher: Unable to create process using '""c:\program files\anaconda3\python.exe"  "C:\Program Files\Anaconda3\Scripts\cmake.exe" --version'
Traceback (most recent call last):
  File "setup.py", line 249, in <module>
    'Topic :: Software Development',
  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Program Files\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Program Files\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Program Files\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Program Files\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Program Files\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 125, in run
    if LooseVersion(self.get_cmake_version()) < '3.1.0':
  File "setup.py", line 117, in get_cmake_version
    out = subprocess.check_output(['cmake', '--version'])
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1

what should i do?

**Comment by ageitgey** [comment]
It looks like you don't have cmake installed or cmake isn't working. Make sure the command `cmake --version` works on your system.

**Comment by kedar2594** [comment]
I had same issues, I just mentioned  "sudo" before that command(GIVE ROOT PRIVILEGES ), it works fine.
