### ISSUE TITLE
trying to run facerec_from_webcam.py

### ISSUE THREAD

**Issue by shubhamdiwase** [ageitgey/face_recognition#476]
python3.5 facerec_from_webcam.py

Crash 
Traceback (most recent call last):
  File "facerec_from_webcam.py", line 40, in <module>
    face_locations = face_recognition.face_locations(rgb_frame)
  File "/usr/local/lib/python3.5/dist-packages/face_recognition-1.2.2-py3.5.egg/face_recognition/api.py", line 118, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, model)]
  File "/usr/local/lib/python3.5/dist-packages/face_recognition-1.2.2-py3.5.egg/face_recognition/api.py", line 102, in _raw_face_locations
    return face_detector(img, number_of_times_to_upsample)
RuntimeError: The stride of the 3rd dimension (the channel dimension) of the numpy array must be 1

**Comment by CodeApprenticeRai** [comment]
Any progress?

**Comment by opengeler** [comment]
same problem here after compiling dlib with cuda 8.0 on visual studio 2015 
python 3.7.0b4
was working with pip3 install dlib ...
