### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by anchpop** [ageitgey/face_recognition#488]
* face_recognition version: latest
* Python version: 3.6.5
* Operating System: latest ubuntu

### Description

Issues installing on my ubuntu server. 

### What I Did

Following the instructions here, https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf, 

Everything worked fine until `python setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA` which did

```
[stuff, seems to work ok]
[ 71%] Built target dlib
[ 72%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/dlib_python.dir/build.make:134: recipe for target 'CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 252, in <module>
    'Topic :: Software Development',
  File "/root/.pyenv/versions/general/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.pyenv/versions/general/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/root/.pyenv/versions/general/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.pyenv/versions/general/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/root/.pyenv/versions/general/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/.pyenv/versions/general/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 129, in run
    self.build_extension(ext)
  File "setup.py", line 168, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/root/.pyenv/versions/3.6.5/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
```

`pip install face_recognition` doesn't work either, with the error 
```Command "/root/.pyenv/versions/3.6.5/envs/general/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-shvd0rtm/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-no25v80w/install-record.txt --single-version-externally-managed --compile --install-headers /root/.pyenv/versions/3.6.5/envs/general/include/site/python3.6/dlib" failed with error code 1 in /tmp/pip-install-shvd0rtm/dlib/
```

**Comment by rodrigoruiz** [comment]
Did you solve the issue?

**Comment by anchpop** [comment]
Yes I did, I just needed to increase swap space

**Comment by shivamp99** [comment]
How much swap space did you put?
