### ISSUE TITLE
Can't use face_recognition cli

### ISSUE THREAD

**Issue by mirkancal** [ageitgey/face_recognition#567]
* face_recognition version:
* Python version: 
* Operating System: Fedora 28

### Description

I've just installed face_recognition and dlib. When I run this command below, I get that output.

```
face_recognition ~/people_i_know/ ./unknown_people/
```

### What I Did
I tried to install dlib 19.7. I downloaded it from sourceforge.net and tried to compile according to this:
https://gist.github.com/ageitgey/629d75c1baac34dfa5ca2a1928a7aeaf

```
Traceback (most recent call last):
  File "/usr/bin/face_recognition", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dlib>=19.7' distribution was not found and is required by face-recognition
```

**Comment by mirkancal** [comment]
Rather than compiling boost, dlib I simply install dlib with: pip install dlib

Now I get something about Click


```
[orange@machine ~]$ face_recognition ./pictures_of_people_i_know/ ./unknown_pictures/
Traceback (most recent call last):
  File "/usr/bin/face_recognition", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Click>=6.0' distribution was not found and is required by face-recognition
```

**Comment by ageitgey** [comment]
Did you install face_recognition without it's dependencies? Just running `pip install face_recognition` should install all the dependencies and fix this error.

**Comment by mirkancal** [comment]
I couldn't do it. I had to do it with root privileges.

`sudo pip install face_recognition`

But now I can only use face_recognition with sudo.

`sudo face_recognition ./people_i_know/ ./unknown_people/` works. It does not work without sudo now.

When I tried to `pip install face_recognition` without sudo.

It gaves me this error:

`Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Mv3fiZ/face-recognition-models/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xfpEw6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Mv3fiZ/face-recognition-models/
`
