### ISSUE TITLE
PIL/Image.py - ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by effnorwood** [ageitgey/face_recognition#59]
* face_recognition version: latest
* Python version: import dlib works for Python 2 and 3
* Operating System: Ubuntu 16.04.2 LTS

### Description

known_people directory has three images of each of four different people
pic1.jpg has 10 unidentified people in it, 2 of which are in known_people
pic2.jpg has 4 unidentified people in it, 1 of which is in known_people

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
gpu@gpu:~$ face_recognition known_people pic1.jpg 
Traceback (most recent call last):
  File "/usr/local/bin/face_recognition", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/cli.py", line 66, in main
    test_image(image_to_check, known_names, known_face_encodings)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/cli.py", line 40, in test_image
    unknown_image = scipy.misc.imresize(unknown_image, scale_factor)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 490, in imresize
    imnew = im.resize(size, resample=func[interp])
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1645, in resize
    return self._new(self.im.resize(size, resample))
ValueError: height and width must be > 0

gpu@gpu:~$ face_recognition known_people pic2.jpg 
Traceback (most recent call last):
  File "/usr/local/bin/face_recognition", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/cli.py", line 66, in main
    test_image(image_to_check, known_names, known_face_encodings)
  File "/usr/local/lib/python2.7/dist-packages/face_recognition/cli.py", line 40, in test_image
    unknown_image = scipy.misc.imresize(unknown_image, scale_factor)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 490, in imresize
    imnew = im.resize(size, resample=func[interp])
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1645, in resize
    return self._new(self.im.resize(size, resample))
ValueError: height and width must be > 0

**Comment by ageitgey** [comment]
Are you able to narrow down which image is causing the crash? And are you willing to share that file so I can see what's going on?

**Comment by ageitgey** [comment]
I think this will be fixed by #65

**Comment by ageitgey** [comment]
Try version 0.1.14 and see if it fixes the issue for you.

**Comment by Ritesh2910** [comment]
resize
ValueError: height and width must be > 0

what can we do for this?
