### ISSUE TITLE
Face not detected in an image: number_of_times_to_upsample=2 results in exception

### ISSUE THREAD

**Issue by pmi123** [ageitgey/face_recognition#670]
* face_recognition version: face-recognition==1.2.3, face-recognition-models==0.3.0
* Python version: 3.4.3
* Operating System: Ubuntu 14.04
* Django 2.0.5
* Celery 4.2.1
* Redis 2.10.6

### Description
My python program detects faces in many photographs (not from cell phone, but scanned images). The baby's face is not detected in one photo (052_002), but was detected in a similar photo (052_003) (both are attached). All the other faces were detected in both photos (including the baby in 052_003).
052_002 - baby looking at mother
052_003 - baby looking at camera
![20047_phillips_photo_052_002](https://user-images.githubusercontent.com/3002127/48366838-3a134d00-e66c-11e8-9468-39a522ee81a7.jpg)
![20047_phillips_photo_052_003](https://user-images.githubusercontent.com/3002127/48366839-3aabe380-e66c-11e8-97e9-0026c703d72d.jpg)

### What I Did
When the baby's face in 052_002 was not found, I looked through your web site and found this article  - https://github.com/ageitgey/face_recognition/wiki/Face-Detection-Problems, so I tried adding the parameter "number_of_times_to_upsample=2" in face_encodings, but got this error:
face_encodings() got an unexpected keyword argument 'number_of_times_to_upsample'
```
Paste the command(s) you ran and the output.
```
image_path = os.path.join(document_path, document_file_name)
image = face_recognition.load_image_file(image_path)
face_encodings = face_recognition.face_encodings(image, number_of_times_to_upsample=2)
```

If there was a crash, please include the traceback here.
```
[2018-11-12 11:06:04,077: ERROR/ForkPoolWorker-1] Task biometric_identification.tasks.find_faces_task[dd9be9ee-6529-4a1c-8327-332a5b0b9532] raised unexpected: TypeError("face_encodings() got an unexpected keyword argument 'number_of_times_to_upsample'",)
Traceback (most recent call last):
  File "/home/mark/.virtualenvs/memorabilia-JSON/lib/python3.4/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/mark/.virtualenvs/memorabilia-JSON/lib/python3.4/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/mark/python-projects/memorabilia-JSON/biometric_identification/tasks.py", line 55, in find_faces_task
    face_encodings = face_recognition.face_encodings(image, number_of_times_to_upsample=2)
TypeError: face_encodings() got an unexpected keyword argument 'number_of_times_to_upsample'
```

```
Is it possible to change the parameters for face_encodings to find this face? 

Is there a way to select the face along the lines of Facebook tagging, and then get the location and encodings so I can add them to my database?

Thanks!

Mark

**Comment by ageitgey** [comment]
The parameter `number_of_times_to_upsample` is for the `face_locations()' function, not the `face_encodings()` function. To use it, you need to break out face detection as a separate step. Try changing your code to this:

```python
image_path = os.path.join(document_path, document_file_name)
image = face_recognition.load_image_file(image_path)
face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=2)
face_encodings = face_recognition.face_encodings(image, known_face_locations=face_locations)
```

**Comment by ageitgey** [comment]
And by splitting it into two steps like this, this also gives you an array of face locations that you could save in a database (so you know which face is which)

**Comment by pmi123** [comment]
Thanks!! I totally missed that very important point about face_locations versus face_encodings.

Unfortunately, making both the changes you described still did not find the baby's face in image 052_002. 

Any examples of how to tell face_recognition there is a missing face - something like facebook where one can click on the missing face? Or other mechanisms for pointing out a region of a missed face?

Thanks!

Mark

**Comment by ageitgey** [comment]
Instead of this:

```python
face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=2)
```

You could try the CNN model like this:

```python
face_locations = face_recognition.face_locations(image, model="cnn")
```

It's more robust in difficult situations.

You can also pass in your own list of `face_locations` to `face_encodings()`, but that probably won't work very well unless the face boxes are perfect.

**Comment by ageitgey** [comment]
You don't need a gpu. It will just run more slowly without one.

**Comment by pmi123** [comment]
OK, I have CUDA and cudnn installed and dlib setup with them on Ubuntu 18.04. I tried
`face_locations = face_recognition.face_locations(image, model="cnn")`
and got this error:
```
File "/home/mark/.virtualenvs/memorabilia-JSON/lib/python3.6/site-packages/face_recognition/api.py", line 116, in face_locations
    return [_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]
  File "/home/mark/.virtualenvs/memorabilia-JSON/lib/python3.6/site-packages/face_recognition/api.py", line 100, in _raw_face_locations
    return cnn_face_detector(img, number_of_times_to_upsample)
MemoryError: std::bad_alloc
```
I have this much RAM (in GB)
```
              total        used        free      shared  buff/cache   available
Mem:             15           7           4           0           2           6
Swap:             0           0           0

```
Any suggestions on how to fix this would be greatly appreciated.

Mark

**Comment by ageitgey** [comment]
try passing in `face_locations = face_recognition.face_locations(image, model="cnn", number_of_times_to_upsample=0)` and seeing if that fits in RAM.

**Comment by pmi123** [comment]
That worked, and tie software found the missing baby's face! 
number_of_times_to_upsample=0 and number_of_times_to_upsample=1 worked. number_of_times_to_upsample=2 failed. 
Hmmm   16 GB of total memory is too small. Time to upgrade!
Thanks for all your help!
Mark

**Comment by PLEX-GR00T** [comment]
Thank you so much guys, your conversation works for me CNN is not working in my lappy i have 8 GB ram, i tried the HOG and it works easily. i really am finding the reason and you and i got it, Thanks again.

**Comment by b4dnewz** [comment]
hi @ageitgey, first of all thank you so much and to all the contributors, for the great work, the module is working good and almost always pretty fast.

I've this situation where programmatically calling `face_locations` on an image results in 0 faces detected, while when using the cli **face_detection** results in 3 faces found:

```
root@745e0945fcb2:/usr/src/app# face_detection images/IMG_2271.JPG
images/IMG_2271.JPG,782,1618,997,1403
images/IMG_2271.JPG,767,2057,1025,1799
images/IMG_2271.JPG,738,1168,996,910
```

the relevant line of code which does not detect faces is this, i've tried with default and custom options:

```py
faces_bounding_boxes = face_recognition.face_locations(
        image, # images/IMG_2271.JPG
)
```

```py
faces_bounding_boxes = face_recognition.face_locations(
        image, # images/IMG_2271.JPG
        model="cnn",
        number_of_times_to_upsample=0
)
```

is a couple of days that I'm trying to find out what can cause this but I really have no clues, I've also looked at [face_detection](https://github.com/ageitgey/face_recognition/blob/master/face_recognition/face_detection_cli.py) source code and doesn't do any image processing or whatever...

#### Context
The code is executed in a docker container with the images mounted as volume, with other images works well, that particular image does not work, also when I run the **face_detection** command for testing I'm still inside the container (with the same configuration as the script execution has) and result in 3 faces found.

As project creator can you hint me about what can be the cause of this different behavior?

Many thanks in advance.

**Comment by osean-man** [comment]
I'm using facerec_from_webcam_faster.py from the examples for some testing and if I change the model from hog to cnn, it doesn't recognize the face and lags hard. I'm also seeing my GPU usage happening but it's 10%-15% of the power. I'm not sure how to intelligently ask how to configure this to work with my GPU. I do have a Nvidia RTX3080.
