### ISSUE TITLE
dont know where to save image I want to scan

### ISSUE THREAD

**Issue by naman108** [ageitgey/face_recognition#697]
* face_recognition version:
* Python version:9
* Operating System:OSX
I get an error whenever i try to run my test program this is the error message:
Traceback (most recent call last):
  File "/Users/nathaadmin/Documents/face_recog.py", line 2, in <module>
    image = face_recognition.load_image_file("My_Image.png")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition/api.py", line 83, in load_image_file
    im = PIL.Image.open(file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: 'My_Image.png'

I named the photo I want scanned My_Image.png 

this is my code:

import face_recognition
image = face_recognition.load_image_file("My_Image.png")
face_locations = face_recognition.face_locations(image)

i have my photo saved in my Downloads file

**Comment by DecentMakeover** [comment]
Have you double checked that My_Image.png exists, and is infact an image?

Second, Can you try pasting the full path to the image ?
