### ISSUE TITLE
Dlib installing error

### ISSUE THREAD

**Issue by Sword-holder** [ageitgey/face_recognition#703]
* face_recognition version:~
* Python version:3.6.7
* Operating System:Ubuntu 16.04

### Description

I came across a problem when installing dlib. I have already installed cmake and python boost. But it will break down on 83%. 

```
[  0%] Building CXX object dlib_build/CMakeFiles/dlib.dir/base64/base64_kernel_1.cpp.o
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_1.cpp.o
[  1%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bigint/bigint_kernel_2.cpp.o
[  2%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bit_stream/bit_stream_kernel_1.cpp.o
[  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_1.cpp.o
[  3%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_decoder/entropy_decoder_kernel_2.cpp.o
[  4%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_1.cpp.o
[  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/entropy_encoder/entropy_encoder_kernel_2.cpp.o
[  5%] Building CXX object dlib_build/CMakeFiles/dlib.dir/md5/md5_kernel_1.cpp.o
[  6%] Building CXX object dlib_build/CMakeFiles/dlib.dir/tokenizer/tokenizer_kernel_1.cpp.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/unicode/unicode.cpp.o
[  7%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/image_dataset_metadata.cpp.o
[  8%] Building CXX object dlib_build/CMakeFiles/dlib.dir/data_io/mnist.cpp.o
[  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/global_optimization/global_function_search.cpp.o
[  9%] Building CXX object dlib_build/CMakeFiles/dlib.dir/filtering/kalman_filter.cpp.o
[ 10%] Building CXX object dlib_build/CMakeFiles/dlib.dir/test_for_odr_violations.cpp.o
[ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/svm/auto.cpp.o
[ 11%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_1.cpp.o
[ 12%] Building CXX object dlib_build/CMakeFiles/dlib.dir/bsp/bsp.cpp.o
[ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_1.cpp.o
[ 13%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_kernel_2.cpp.o
[ 14%] Building CXX object dlib_build/CMakeFiles/dlib.dir/dir_nav/dir_nav_extensions.cpp.o
[ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/linker/linker_kernel_1.cpp.o
[ 15%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/extra_logger_headers.cpp.o
[ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_kernel_1.cpp.o
[ 16%] Building CXX object dlib_build/CMakeFiles/dlib.dir/logger/logger_config_file.cpp.o
[ 17%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_1.cpp.o
[ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/misc_api/misc_api_kernel_2.cpp.o
[ 18%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_extensions.cpp.o
[ 19%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockets/sockets_kernel_2.cpp.o
[ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf.cpp.o
[ 20%] Building CXX object dlib_build/CMakeFiles/dlib.dir/sockstreambuf/sockstreambuf_unbuffered.cpp.o
[ 21%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_kernel.cpp.o
[ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_iostream.cpp.o
[ 22%] Building CXX object dlib_build/CMakeFiles/dlib.dir/server/server_http.cpp.o
[ 23%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/multithreaded_object_extension.cpp.o
[ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threaded_object_extension.cpp.o
[ 24%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_1.cpp.o
[ 25%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_2.cpp.o
[ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/threads_kernel_shared.cpp.o
[ 26%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/thread_pool_extension.cpp.o
[ 27%] Building CXX object dlib_build/CMakeFiles/dlib.dir/threads/async.cpp.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/timer/timer.cpp.o
[ 28%] Building CXX object dlib_build/CMakeFiles/dlib.dir/stack_trace.cpp.o
[ 29%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/cpu_dlib.cpp.o
[ 30%] Building CXX object dlib_build/CMakeFiles/dlib.dir/cuda/tensor_tools.cpp.o
[ 30%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/arm/arm_init.c.o
[ 31%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/arm/filter_neon_intrinsics.c.o
[ 32%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/png.c.o
[ 32%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngerror.c.o
[ 33%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngget.c.o
[ 33%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngmem.c.o
[ 34%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngpread.c.o
[ 35%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngread.c.o
[ 35%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngrio.c.o
[ 36%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngrtran.c.o
[ 37%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngrutil.c.o
[ 37%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngset.c.o
[ 38%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngtrans.c.o
[ 39%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwio.c.o
[ 39%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwrite.c.o
[ 40%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwtran.c.o
[ 41%] Building C object dlib_build/CMakeFiles/dlib.dir/external/libpng/pngwutil.c.o
[ 41%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/adler32.c.o
[ 42%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/compress.c.o
[ 43%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/crc32.c.o
[ 43%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/deflate.c.o
[ 44%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzclose.c.o
[ 45%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzlib.c.o
[ 45%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzread.c.o
[ 46%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/gzwrite.c.o
[ 47%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/infback.c.o
[ 47%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inffast.c.o
[ 48%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inflate.c.o
[ 49%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/inftrees.c.o
[ 49%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/trees.c.o
[ 50%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/uncompr.c.o
[ 50%] Building C object dlib_build/CMakeFiles/dlib.dir/external/zlib/zutil.c.o
[ 51%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/png_loader.cpp.o
[ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_png.cpp.o
[ 52%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcomapi.cpp.o
[ 53%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapimin.cpp.o
[ 54%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdapistd.cpp.o
[ 54%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatasrc.cpp.o
[ 55%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcoefct.cpp.o
[ 56%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdcolor.cpp.o
[ 56%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jddctmgr.cpp.o
[ 57%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdhuff.cpp.o
/home/ubuntu/dlib/dlib/external/libjpeg/jdhuff.cpp:23:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wshift-negative-value"
                                ^
[ 58%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdinput.cpp.o
[ 58%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmainct.cpp.o
[ 59%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmarker.cpp.o
[ 60%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmaster.cpp.o
[ 60%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdmerge.cpp.o
[ 61%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdphuff.cpp.o
/home/ubuntu/dlib/dlib/external/libjpeg/jdphuff.cpp:23:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wshift-negative-value"
                                ^
[ 62%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdpostct.cpp.o
[ 62%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdsample.cpp.o
[ 63%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jerror.cpp.o
[ 64%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctflt.cpp.o
[ 64%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctfst.cpp.o
[ 65%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctint.cpp.o
[ 66%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jidctred.cpp.o
[ 66%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemmgr.cpp.o
[ 67%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jmemnobs.cpp.o
[ 67%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant1.cpp.o
[ 68%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jquant2.cpp.o
[ 69%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jutils.cpp.o
[ 69%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapimin.cpp.o
[ 70%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jdatadst.cpp.o
[ 71%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcparam.cpp.o
[ 71%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcapistd.cpp.o
[ 72%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmarker.cpp.o
[ 73%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcinit.cpp.o
[ 73%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmaster.cpp.o
[ 74%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcdctmgr.cpp.o
[ 75%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccoefct.cpp.o
[ 75%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jccolor.cpp.o
[ 76%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jchuff.cpp.o
[ 77%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcmainct.cpp.o
[ 77%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcphuff.cpp.o
[ 78%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcprepct.cpp.o
[ 79%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jcsample.cpp.o
[ 79%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctint.cpp.o
[ 80%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctflt.cpp.o
[ 81%] Building CXX object dlib_build/CMakeFiles/dlib.dir/external/libjpeg/jfdctfst.cpp.o
[ 81%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_loader/jpeg_loader.cpp.o
[ 82%] Building CXX object dlib_build/CMakeFiles/dlib.dir/image_saver/save_jpeg.cpp.o
[ 83%] Linking CXX static library libdlib.a
[ 83%] Built target dlib
[ 83%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
In file included from /home/ubuntu/dlib/dlib/external/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/ubuntu/dlib/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /home/ubuntu/dlib/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /home/ubuntu/dlib/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /home/ubuntu/dlib/dlib/../dlib/python/pybind_utils.h:6,
                 from /home/ubuntu/dlib/dlib/../dlib/python.h:6,
                 from /home/ubuntu/dlib/tools/python/src/opaque_types.h:6,
                 from /home/ubuntu/dlib/tools/python/src/dlib.cpp:4:
/home/ubuntu/dlib/dlib/external/pybind11/include/pybind11/detail/common.h:111:20: fatal error: Python.h: No such file or directory
compilation terminated.
CMakeFiles/dlib_python.dir/build.make:62: recipe for target 'CMakeFiles/dlib_python.dir/src/dlib.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/dlib.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 257, in <module>
    'Topic :: Software Development',
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 133, in run
    self.build_extension(ext)
  File "setup.py", line 173, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 257, in <module>
    'Topic :: Software Development',
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 133, in run
    self.build_extension(ext)
  File "setup.py", line 173, in build_extension
    subprocess.check_call(cmake_build, cwd=build_folder)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2.
```

please help me!!!

### What I Did

```
sudo apt-get install cmake
sudo apt-get install libboost-python-dev
sudo python3 setup.py install
```

**Comment by rshgithub** [comment]
did you solve it ? because i ran into the same error !

**Comment by colorfulberry** [comment]
@Sword-holder  you need to `apt-get install python3-dev`

**Comment by Sword-holder** [comment]
[Resolved]
I didn't have python3.6-dev. Because I'm using python3.6.7, and my computer has python3.6, 3.5, 2.7 at the same. 
If I type 
`apt-get install sudo apt-get install libboost-python-dev `
python2.7-dev will be installed by default. If I type
`apt-get install python3-dev`
Then python3.5-dev will be installed. 
So You need to specify the version of python dev by typing 
`apt-get install python3.6-dev`
@rshgithub 
Thank you! @colorfulberry

**Comment by qzlinqian** [comment]
I also met something like this on CentOS 7. I solved it by `yum install python36-devel`.

**Comment by ashir-sirius** [comment]
Building CXX object CMakeFiles/_dlib_pybind11.dir/src/face_recognition.cpp.o got stuck here into this loop .. Need help
