### ISSUE TITLE
face_recognition errors !

### ISSUE THREAD

**Issue by rshgithub** [ageitgey/face_recognition#708]
* face_recognition version: (1.2.3)
* Python version: ( 3.7 )
cmake  ( 2.8.3)
opencv ( 3.4.4 )
dlib ( 19.16.0 )
conda ( 4.5.11 )
numpy (1.15.1)
scipy (1.1.0)
pillow (5.2.0)
face recognition models (0.3.0)
scikit-learn (0.19.2)
scikit-image (0.14.0)
* Operating System: ubuntu ( linux ) using virtualbox

hello everyone , thankx for the amazing app,  i'm new student of machine learning and and this is the first app i install by my own using machine learning , i came up with many errors  :
i'm not able to run the app successfully and i don't know where is the mistake !

1- first when i try  ( python setup.py install ) it's installing until it stops with this error:

```
File "/home/rawan/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/rawan/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-g1p1izyy/dlib-19.16.0/setup.py", line 133, in run
  File "/tmp/easy_install-g1p1izyy/dlib-19.16.0/setup.py", line 173, in build_extension
  File "/home/rawan/anaconda3/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status `2`
```

second : when i run import face_recognition i get this error 

```
rawan@rawan:~$ python
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rawan/anaconda3/lib/python3.7/site-packages/face_recognition-1.2.3-py3.7.egg/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/rawan/anaconda3/lib/python3.7/site-packages/face_recognition-1.2.3-py3.7.egg/face_recognition/api.py", line 14, in <module>
    face_detector = dlib.get_frontal_face_detector()
AttributeError: module 'dlib' has no attribute 'get_frontal_face_detector'
>>> 
```

and when i try to pip install --user face_recognition it gives me :
```


raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2.
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... /

```

and at the end

```
Command "/home/rawan/anaconda3/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-install-d0ozrmdb/dlib/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-record-dsq8ol9r/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-d0ozrmdb/dlib/
```
and when i try `import face_recognition` i get this
```import-im6.q16: not authorized face_recognition @ error/constitute.c/WriteImage/1037.```

i tried a lot of solutions around the internet but the same problems come back  , i will appreciate any help from you ,thank you very much .

**Comment by rshgithub** [comment]
i have  dlib in `./.local/lib/python2.7/site-packages` `` , i think the error is here 
becuasei'm using python 3.7
should i go back to python 2.7 ??
