### ISSUE TITLE
forget headers for run gpu

### ISSUE THREAD

**Issue by inoshu** [ageitgey/face_recognition#709]
* face_recognition version: 1.2.3
* Python version: 3.7.2
* Operating System: 10.0.16299

### Description
 i install gpu for dlib after i run code then i receive forgot few headers 
### 

```
[INFO] loading encodings ...
Traceback (most recent call last):
  File "face-recognition.py", line 26, in <module>
    boxes = face_recognition.batch_face_locations(rgb, number_of_times_to_upsample=1)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\face_recognition\api.py", line 146, in batch_face_locations
    raw_detections_batched = _raw_face_locations_batched(images, number_of_times_to_upsample, batch_size)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\face_recognition\api.py", line 129, in _raw_face_locations_batched
    return cnn_face_detector(images, number_of_times_to_upsample, batch_size=batch_size)
TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: dlib.cnn_face_detection_model_v1, imgs: list, upsample_num_times: int=0, batch_size: int=128) -> std::vector<std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> >,std::allocator<std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> > > >
    2. (self: dlib.cnn_face_detection_model_v1, img: array, upsample_num_times: int=0) -> std::vector<dlib::mmod_rect,std::allocator<dlib::mmod_rect> >

Invoked with: <dlib.cnn_face_detection_model_v1 object at 0x000001D9C815E928>, array([[[ 92, 110, 106],
        [ 92, 110, 106],
        [ 88, 111, 106],
        ...,
        [ 78, 103, 108],
        [ 75,  98,  99],
        [ 69,  92,  94]],

       [[ 96, 110, 107],
        [ 96, 110, 107],
        [ 90, 111, 106],
        ...,
        [ 74, 101, 104],
        [ 72,  97, 100],
        [ 69,  93,  97]],

       [[101, 108, 102],
        [ 99, 107, 101],
        [101, 108, 100],
        ...,
        [ 74,  97,  98],
        [ 77,  97, 102],
        [ 77,  97, 102]],

       ...,

       [[103, 121, 130],
        [101, 118, 128],
        [ 98, 118, 127],
        ...,
        [ 92, 117, 122],
        [ 90, 117, 122],
        [ 90, 117, 122]],

       [[108, 120, 134],
        [106, 118, 131],
        [104, 117, 128],
        ...,
        [ 86, 120, 121],
        [ 88, 119, 121],
        [ 88, 119, 121]],

       [[110, 120, 134],
        [107, 118, 131],
        [107, 118, 131],
        ...,
        [ 84, 120, 123],
        [ 84, 120, 123],
        [ 84, 120, 123]]], dtype=uint8), 1; kwargs: batch_size=128

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
[ WARN:0] terminating async callback

```

**Comment by ageitgey** [comment]
This probably just means that the format or type of the data you passed into `batch_face_locations()` is wrong.

**Comment by inoshu** [comment]
> This probably just means that the format or type of the data you passed into `batch_face_locations()` is wrong.

thanks , i see again code
