### ISSUE TITLE
ImportError: dlib v19.16.0 is missing cblas_dtrsm symbol

### ISSUE THREAD

**Issue by s0h3ck** [ageitgey/face_recognition#731]
* face_recognition version: 

Click==7.0
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
numpy==1.16.0
Pillow==5.4.1

* Python version: 3.7.2
* Pip version: 19.0.1
* Operating System: Linux archlinux 4.19.18-1-lts 

### Description

The pip installation gave me an undefined symbol: cblas_dtrsm.

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import face_recognition
  File "/home/s0h3ck/.virtualenvs/test/lib/python3.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/s0h3ck/.virtualenvs/test/lib/python3.7/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: /home/s0h3ck/.virtualenvs/test/lib/python3.7/site-packages/dlib.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cblas_dtrsm
```

### What I Did

```
workon test (or mkvirtualenv test before)
pip install face_recognition
```

dlib (19.16.0) md5sum : 96ff1db547ab5d289d049e58f823ae46

### Temporary solution

Install dlib version 19.15.0

```
pip install dlib=19.15.0
```

dlib (19.15.0) md5sum : e0ea6c4c6e7c1f445a11fae2733cb9b6

### Additional comments

A word about Archlinux, if you do `yay -S  python-face_recognition`, it will work, but it won't be in a virtualenv. Please do not close this issue if we can't do `pip install face_recognition` normally to his latest version. Thanks.

**Comment by ShadowProgr** [comment]
I encountered the same problem on antergos with dlib 19.17.0. The solution for me was installing cblas via pacman

**Comment by fsondej** [comment]
I had a similar problem. Solved it by installing openblas. On arch just:
pacman -S openblas
And then, reinstalling dlib.

**Comment by antonov-impulsm** [comment]
> pacman -S openblas

thank you for recipe. I tried that but had another experience:

`pacman -S cblas` # and reinstalling `dlib` (pip) -- successfully fixed the issue (but with a regular `blas`, not `openblas`).

but just changing `blas` with `openblas` (without a `cblas`)  -- did not helped

**Comment by KrishnarajT** [comment]
I have the same problem on arch and ended up installing dlib 19.15.0 as mentioned previously.

**Comment by DDusky** [comment]
`pip install dlib==19.15.0` work
