### ISSUE TITLE
receiving error when the code reaches to encoding part of face_recognition library

### ISSUE THREAD

**Issue by AbhinavJhanwar** [ageitgey/face_recognition#737]
* face_recognition version: 1.2.3
* Python version: 3.6.5
* Operating System: windows 10

### What I Did
I have just setup my CUDA with dlib and after that I am receiving this error when running the encoding of face using face_recognition library
```
face_encodings = face_recognition.face_encodings(frame, face_locations, num_jitters=1)

  File "C:\Users\abhinav.jhanwar\AppData\Local\Continuum\anaconda3\lib\site-packages\face_recognition\api.py", line 210, in face_encodings
    :return: A list of 128-dimensional face encodings (one for each face in the image)

  File "C:\Users\abhinav.jhanwar\AppData\Local\Continuum\anaconda3\lib\site-packages\face_recognition\api.py", line 210, in <listcomp>
    :return: A list of 128-dimensional face encodings (one for each face in the image)

RuntimeError: Error while calling cudnnCreate(&handles[new_device_id]) in file C:\dlib-master\dlib-master\dlib\cuda\cudnn_dlibapi.cpp:104. code: 1, reason: CUDA Runtime API initialization failed.
```

**Comment by Vityan** [comment]
Today I faced the same problem,help me please

**Comment by Vityan** [comment]
Hello ! 
os: windows 8.1

Today I completed the installation of face_recognition, a library for python3. Also, before that I installed dlib with CUDA, very successfully. After that, I tried to run a script with recognition of people, and I received an error This i got on the command line 
`Traceback (most recent call last):
  File "C:\Users\в.е.гусаров\Documents\Visual Studio 2015\Projects\PythonApplica
tion1\PythonApplication1\face-recognition-opencv\recognize_faces_video_file.py",
 line 6, in <module>
    import face_recognition
  File "C:\Program Files\Python37\lib\site-packages\face_recognition\__init__.py
", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face
_landmarks, face_encodings, compare_faces, face_distance
  File "C:\Program Files\Python37\lib\site-packages\face_recognition\api.py", li
ne 23, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_mode
l)
RuntimeError`
Help me please

**Comment by kormalev** [comment]
This may happen due to missing cuDNN or version mismatch. I encountered this error having libcudnn7 for CUDA 10.1 while the system's CUDA version was 10.0.

**Comment by Professor-Paradox** [comment]
check your gpu sm version and cuda support for it, cuda10.1 only supports from sm_30 to sm_75.
make sure the cuda and cudnn are compatible
