### ISSUE TITLE
jpeg file can't be loaded by 

### ISSUE THREAD

**Issue by ckl8964** [ageitgey/face_recognition#75]
* face_recognition version: 0.1.14
* Python version: 2.7.12
* Operating System: ubuntu 16.04.2

### Description
Can't load the image file by load_image_file, even the file is there.

### What I Did
import face_recognition
biden_image = face_recognition.load_image_file("biden.jpg")

After I run the above 2 lines in the python shell, it shows the error message below :

Traceback (most recent call last):
  File "freco.py", line 5, in <module>
    biden_image = face_recognition.load_image_file("biden.jpg")
  File "/home/kl/opencv/local/lib/python2.7/site-packages/face_recognition/api.py", line 78, in load_image_file
    return scipy.misc.imread(filename, mode=mode)
  File "/home/kl/opencv/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/home/kl/opencv/local/lib/python2.7/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'biden.jpg'

**Comment by ckl8964** [comment]
Sorry, silly mistake made corrupted the jpg file.
