### ISSUE TITLE
Comparing new encoding with saved encodings from .dat file

### ISSUE THREAD

**Issue by franckyz0r** [ageitgey/face_recognition#791]
* face_recognition version: probably 1.2.2
* Python version: 3.6.3
* Operating System: CentOS 7

### Description

Hello, I have access to lots of pictures and 64 cores CPU. I am not that great at python.
I noticed that face_recognition can't use multiple core while it is loading images, faces, encodings,it only uses multiple cores while comparing the encodings. Because of this I can't do a real-time comparison of a picture with all the others fast enough.

### What I Did

I started creating a script to dump all encodings to a file (tested with 1k samples first), using your guide [here](https://github.com/ageitgey/face_recognition/wiki/How-do-I-save-face-encodings-to-a-file%3F):
```
import face_recognition
import pickle
import os
import glob
import concurrent.futures

#go to img directory
os.chdir("/home/samples")
#all img files
IMG_FILES = glob.glob("*.jpg")
FILES_COUNT = len(IMG_FILES)
print (f'\033[96m We have {FILES_COUNT} jpg files.\033[00m')
#dump file
DUMP_ENCODINGS = "/home/known_faces.dat"
#other vars
all_face_encodings = {}

#create face encoding
def face_encode(img):
    try:
        img_load = face_recognition.load_image_file(img)
    except:
        print (f'\033[91m File {img} - could not be loaded (corrupted?).\033[00m')
        return False
    try:
        a_face_encoding = face_recognition.face_encodings(img_load)[0]
    except:
        print (f'\033[91m File {img} - no face detected.\033[00m')
        return False
    return a_face_encoding

#work the cpus
with concurrent.futures.ProcessPoolExecutor() as executor:
    for IMG_FILE, the_face_encoding in zip(IMG_FILES, executor.map(face_encode, IMG_FILES)):
        if the_face_encoding is False:
            all_face_encodings[os.path.splitext(os.path.basename(IMG_FILE))[0]] = None
            continue
        all_face_encodings[os.path.splitext(os.path.basename(IMG_FILE))[0]] = the_face_encoding

#dump
with open(DUMP_ENCODINGS, 'ab+') as file_dump:
    pickle.dump(all_face_encodings, file_dump)
```
**This worked very well and pretty fast - all cores used.**
See 3 random arrays from the results.
[3random_arrays.txt](https://github.com/ageitgey/face_recognition/files/3032491/3random_arrays.txt)

Now I want to check new images against all this encodings. I tried the idea from [here](https://github.com/ageitgey/face_recognition/wiki/How-do-I-save-face-encodings-to-a-file%3F), but I always get this error:
```
Traceback (most recent call last):
  File "compare_face.py", line 37, in <module>
    main()
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/Click-7.0-py3.6.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "compare_face.py", line 33, in main
    result = test_img(unknown_face, face_names, face_encds)
  File "compare_face.py", line 9, in test_img
    result = face_recognition.compare_faces(face_encodings, unknown_face)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/face_recognition-1.2.3-py3.6.egg/face_recognition/api.py", line 222, in compare_faces
    return list(face_distance(known_face_encodings, face_encoding_to_check) <= tolerance)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/face_recognition-1.2.3-py3.6.egg/face_recognition/api.py", line 72, in face_distance
    return np.linalg.norm(face_encodings - face_to_compare, axis=1)
ValueError: operands could not be broadcast together with shapes (10,) (128,)
```
I'm guessing I don't read the encodings properly from the .dat file.
Code:
```
import face_recognition
import pickle
import os
import click
import numpy as np

def test_img(unknown_face, face_names, face_encodings):
    result = face_recognition.compare_faces(face_encodings, unknown_face)
    names_with_result = list(zip(face_names, result))
    return [names_with_result]

@click.command()
@click.argument('image_to_check')

def main (image_to_check, tolerance):
    #unknown
    unknown_image = face_recognition.load_image_file(image_to_check)
    unknown_face = face_recognition.face_encodings(unknown_image)[0]
    #dump file
    DUMP_ENCODINGS = "/home/known_faces.dat"
    #other vars
    with open(DUMP_ENCODINGS, 'rb') as file_dump_read:
        all_face_encodings = pickle.load(file_dump_read)
    face_names = list(all_face_encodings.keys())
    face_encds = np.array(list(all_face_encodings.values()))
    result = test_img(unknown_face, face_names, face_encds)
    print (result)

if __name__ == "__main__":
    main()
```

If you have any ideas please do help! If you think I should change the approach, please tell!
Do you think I should save the encodings in a different way for faster comparison (like a db)?
I still need to make this second part to use multiple cores.

In the end I will probably have like 400 000 encodings saved and I will need to compare a new face with the old ones ASAP. I am willing to use KNN if it will be more accurate (right now I it does not detect faces in many, many pictures).

Regards,

**Comment by hanckmail** [comment]
i've noticed that your code works well, when all images are recognized, but if there is any mistakes recognition won't work

**Comment by Mutleymuffin** [comment]
Hello @hanckmail I have just come across this solution, and I was wondering if you'd share some code as to how you implemented this?

Thanks

**Comment by franckyz0r** [comment]
Hello,
I'm a bit late, sorry, but hanckmail was right.
I made an workaround and I haven't saved the None values any more. You can also save them in your .dat file and when your read .dat file don't compare if value is None.

Bogdan

**Comment by Mutleymuffin** [comment]
Hi,
Could you give me some code of how you did that, as I am struggling
thanks
