### ISSUE TITLE
facerec_from_webcam_multiprocessing.py run Global is not defined

### ISSUE THREAD

**Issue by derekzhan** [ageitgey/face_recognition#809]
* face_recognition version: 1.23
* Python version: 3.6.6
* Operating System: windows 10

### Description
![image](https://user-images.githubusercontent.com/2375460/56864177-e74b0900-69f1-11e9-9cad-d44cc8ca9d3d.png)

### What I Did

```
facerec_from_webcam_multiprocessing.py run Global is not defined. pls fix it, thanks
```

**Comment by chn-lee-yumi** [comment]
Sorry for too late to see this issue. Could you paste full output of the console? I haven't test it on Windows. On Linux, python3.5 is ok.

**Comment by chn-lee-yumi** [comment]
@DevelopmentIsKey @Muplex 
Are you using Windows too?

**Comment by Muplex** [comment]
Yes,

**Comment by chn-lee-yumi** [comment]
> Yes, python 3.7.3 and 3.6 also same result:
> 
> ```
> Traceback (most recent call last):
>   File "facerec_from_webcam_multiprocessing.py", line 115, in <module>
>     Global = Manager().Namespace()
> NameError: name 'Manager' is not defined
> ```
Could you paste full output of the console?

**Comment by chn-lee-yumi** [comment]
@Muplex 
> Yes, python 3.7.3 and 3.6 also same result:
> 
> ```
> Traceback (most recent call last):
>   File "facerec_from_webcam_multiprocessing.py", line 115, in <module>
>     Global = Manager().Namespace()
> NameError: name 'Manager' is not defined
> ```

Normally 'Manager' should not be `not defined`, it was imported using `from multiprocessing import Process, Manager, cpu_count` on line 3.  
Try this code on python console or create a new script:
```python
from multiprocessing import Manager
Global = Manager().Namespace()
```
Will this work?

**Comment by Muplex** [comment]
Yes, sorry, my fault the prev reply; with the correct imports now the console output is:

```
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-5:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-9:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-12:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-11:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-7:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-10:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
Process Process-6:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files (x86)\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Muplex\Desktop\EsemPy\Dev\Esempi Computer vision\face_recognition-master\examples\facerec_from_webcam_multiprocessing.py", line 59, in process
    known_face_encodings = Global.known_face_encodings
NameError: name 'Global' is not defined
```

At this point script stuck and I have to kill the process

**Comment by sujoyu** [comment]
I have same problem too.
I fixed this problem for now by passing `Global` object to each functions' args.

**Comment by Muplex** [comment]
Hi Sujoyu,
in which function did you pass `Global` as arg?
Can you make me an example (I'm not a py expert, sorry, I'm studing on it =) )

**Comment by sujoyu** [comment]
Hi Muplex.
The fixed example is following link.
https://gist.github.com/sujoyu/ad36b2fef0f0e215d6ee1d093d925e63
I'm not a Python expert too.
It may not be a best way.

Additionally, in my low spec but 2 cores ４threads Machine, following code is faster than the original.

Change line 125
```
worker_num = cpu_count()
```
to
```
worker_num = cpu_count() - 1
```

`- 1` indicates count of capturing process.

**Comment by chn-lee-yumi** [comment]
@sujoyu 
Thank you. Now I realized what's wrong. Global is a global variable, but I don't know why on some machines (maybe python version?) it works, but others will show `name 'Global' is not defined`.  

@Muplex 
Pass the variable using function arg or just add `global Global` on the start of the functions (`capture()`and`process()`) may work. I will fix this soon.
