### ISSUE TITLE
Unable to import face_recognition

### ISSUE THREAD

**Issue by yarin177** [ageitgey/face_recognition#856]
* face_recognition version:1.2.3
* Python version:3.6.4
* Operating System:Windows 10 64bit

### Description

I am trying to import face_recognition after i "successfully" installed it.

### What I Did

C:\Users\ירין>pip install face_recognition
Requirement already satisfied: face_recognition in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (1.2.3)
Requirement already satisfied: face-recognition-models>=0.3.0 in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (from face_recognition) (0.3.0)
Requirement already satisfied: Pillow in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (from face_recognition) (5.3.0)
Requirement already satisfied: Click>=6.0 in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (from face_recognition) (7.0)
Requirement already satisfied: numpy in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (from face_recognition) (1.15.4)
Requirement already satisfied: dlib>=19.7 in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (from face_recognition) (19.7.0)
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\ירין>pip install cmake
Requirement already satisfied: cmake in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (3.14.4)
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\ירין>pip install dlib
Requirement already satisfied: dlib in c:\users\ירין\appdata\local\programs\python\python36\lib\site-packages (19.7.0)
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command

Then when i am trying to import it..
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\face_recognition\__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\face_recognition\api.py", line 17, in <module>
    pose_predictor_68_point = dlib.shape_predictor(predictor_68_point_model)
RuntimeError: Unable to open C:\Users\ירין\AppData\Local\Programs\Python\Python36\lib\site-packages\face_recognition_models\models\shape_predictor_68_face_landmarks.dat

**Comment by rafayk7** [comment]
Try installing with pip3 instead of pip.

Do `pip3 install face_detection` and see if it works.

**Comment by yarin177** [comment]
> Try installing with pip3 instead of pip.
> 
> Do `pip3 install face_detection` and see if it works.

Did you mean "pip3 install face_recognition" because "face_detection" is not a module?

**Comment by rafayk7** [comment]
> > Try installing with pip3 instead of pip.
> > Do `pip3 install face_detection` and see if it works.
> 
> Did you mean "pip3 install face_recognition" because "face_detection" is not a module?

Haha my bad! Yes, face_recognition haha.

**Comment by yarin177** [comment]
> > > Try installing with pip3 instead of pip.
> > > Do `pip3 install face_detection` and see if it works.
> > 
> > 
> > Did you mean "pip3 install face_recognition" because "face_detection" is not a module?
> 
> Haha my bad! Yes, face_recognition haha. Let me know if using pip3 worked.

Unfortunately same result

**Comment by ujwalakoriraj** [comment]
I am facing the same issue. Has anyone solved this?

**Comment by ChandraSekhar777** [comment]
> I am facing the same issue. Has anyone solved this?

Watch this Video  https://www.youtube.com/watch?v=xaDJ5xnc8dc  
You will get an idea.

**Comment by ujwalakoriraj** [comment]
Will do. Thank you.

**Comment by hritik-111** [comment]
> Try installing with pip3 instead of pip.
> 
> Do `pip3 install face_detection` and see if it works.

this worked for me thank you.
