### ISSUE TITLE
issue in face_recognition/setup.py

### ISSUE THREAD

**Issue by arjhun19** [ageitgey/face_recognition#860]
* face_recognition version:latest
* Python version:3.7.1
* Operating System:mac os

### Description

I want to run the setup.py file and it was throwing lots of error and cleared one by one , but now this happened I don't know what to do and im stuck

### What I Did

```
(base) Arjhuns-MacBook-Air:Home arjhun$ python /Users/arjhun/face_recognition/setup.py install
running install
running bdist_egg
running egg_info
creating face_recognition.egg-info
error: could not create 'face_recognition.egg-info': Operation not supported
(base) Arjhuns-MacBook-Air:Home arjhun$ pip install egg_info
Collecting egg_info
  ERROR: Could not find a version that satisfies the requirement egg_info (from versions: none)
ERROR: No matching distribution found for egg_info

```
please help me

**Comment by arjhun19** [comment]
when I run pip install face_recognition it shows this 
```
(base) Arjhuns-MacBook-Air:Home arjhun$ pip install face_recognition
Collecting face_recognition
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Requirement already satisfied: Pillow in /Users/arjhun/anaconda3/lib/python3.7/site-packages (from face_recognition) (5.3.0)
Requirement already satisfied: Click>=6.0 in /Users/arjhun/anaconda3/lib/python3.7/site-packages (from face_recognition) (7.0)
Collecting face-recognition-models>=0.3.0 (from face_recognition)
Collecting dlib>=19.7 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Requirement already satisfied: numpy in /Users/arjhun/anaconda3/lib/python3.7/site-packages (from face_recognition) (1.15.4)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Complete output from command /Users/arjhun/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-wheel-kgxpql6u --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  package init file 'dlib/__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.7.1 (default, Dec 14 2018, 13:28:58)
  Invoking CMake setup: 'cmake /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/lib.macosx-10.9-x86_64-3.7 -DPYTHON_EXECUTABLE=/Users/arjhun/anaconda3/bin/python -DCMAKE_BUILD_TYPE=Release'
  -- The C compiler identification is Clang 4.0.1
  -- The CXX compiler identification is Clang 4.0.1
  -- Check for working C compiler: /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang
  -- Check for working C compiler: /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang -- broken
  CMake Error at /Users/arjhun/anaconda3/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
    The C compiler
  
      "/Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang"
  
    is not able to compile a simple test program.
  
    It fails with the following output:
  
      Change Dir: /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp
  
      Run Build Command(s):/Users/arjhun/anaconda3/bin/make cmTC_12d43/fast
      /Users/arjhun/anaconda3/bin/make -f CMakeFiles/cmTC_12d43.dir/build.make CMakeFiles/cmTC_12d43.dir/build
      make[1]: Entering directory '/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp'
      Building C object CMakeFiles/cmTC_12d43.dir/testCCompiler.c.o
      /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_12d43.dir/testCCompiler.c.o   -c /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp/testCCompiler.c
      Linking C executable cmTC_12d43
      /Users/arjhun/anaconda3/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_12d43.dir/link.txt --verbose=1
      /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs  CMakeFiles/cmTC_12d43.dir/testCCompiler.c.o  -o cmTC_12d43
      ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
      ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
      clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
      make[1]: *** [CMakeFiles/cmTC_12d43.dir/build.make:87: cmTC_12d43] Error 1
      make[1]: Leaving directory '/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp'
      make: *** [Makefile:121: cmTC_12d43/fast] Error 2
  
  
  
  
    CMake will not be able to correctly generate this project.
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "/Users/arjhun/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/arjhun/anaconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py", line 135, in run
      self.build_extension(ext)
    File "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "/Users/arjhun/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/lib.macosx-10.9-x86_64-3.7', '-DPYTHON_EXECUTABLE=/Users/arjhun/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: face-recognition-models, dlib, face-recognition
  Running setup.py install for dlib ... error
    ERROR: Complete output from command /Users/arjhun/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-record-xdtczi3n/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.1 (default, Dec 14 2018, 13:28:58)
    Invoking CMake setup: 'cmake /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/lib.macosx-10.9-x86_64-3.7 -DPYTHON_EXECUTABLE=/Users/arjhun/anaconda3/bin/python -DCMAKE_BUILD_TYPE=Release'
    -- The C compiler identification is Clang 4.0.1
    -- The CXX compiler identification is Clang 4.0.1
    -- Check for working C compiler: /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang
    -- Check for working C compiler: /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang -- broken
    CMake Error at /Users/arjhun/anaconda3/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
      The C compiler
    
        "/Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang"
    
      is not able to compile a simple test program.
    
      It fails with the following output:
    
        Change Dir: /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp
    
        Run Build Command(s):/Users/arjhun/anaconda3/bin/make cmTC_616f3/fast
        /Users/arjhun/anaconda3/bin/make -f CMakeFiles/cmTC_616f3.dir/build.make CMakeFiles/cmTC_616f3.dir/build
        make[1]: Entering directory '/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp'
        Building C object CMakeFiles/cmTC_616f3.dir/testCCompiler.c.o
        /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -o CMakeFiles/cmTC_616f3.dir/testCCompiler.c.o   -c /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp/testCCompiler.c
        Linking C executable cmTC_616f3
        /Users/arjhun/anaconda3/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_616f3.dir/link.txt --verbose=1
        /Users/arjhun/anaconda3/bin/x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs  CMakeFiles/cmTC_616f3.dir/testCCompiler.c.o  -o cmTC_616f3
        ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
        ld: dynamic main executables must link with libSystem.dylib for architecture x86_64
        clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
        make[1]: *** [CMakeFiles/cmTC_616f3.dir/build.make:87: cmTC_616f3] Error 1
        make[1]: Leaving directory '/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeTmp'
        make: *** [Makefile:121: cmTC_616f3/fast] Error 2
    
    
    
    
      CMake will not be able to correctly generate this project.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    See also "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/temp.macosx-10.9-x86_64-3.7/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/Users/arjhun/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/arjhun/anaconda3/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/arjhun/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py", line 135, in run
        self.build_extension(ext)
      File "/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "/Users/arjhun/anaconda3/lib/python3.7/subprocess.py", line 341, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/tools/python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/build/lib.macosx-10.9-x86_64-3.7', '-DPYTHON_EXECUTABLE=/Users/arjhun/anaconda3/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "/Users/arjhun/anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-record-xdtczi3n/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/dm/s1gt703d4939v6fhrw8zkd9w0000gn/T/pip-install-tm56xkb2/dlib/
(base) Arjhuns-MacBook-Air:Home arjhun$ 


```
