### ISSUE TITLE
failed in many know_people(1W<>)

### ISSUE THREAD

**Issue by godcong** [ageitgey/face_recognition#892]
* face_recognition version:  unknow(the newest from apt install)
* Python version: 3.5.2
* Operating System: Ubuntu 16.04.6 LTS

### Description
ps: there are 1w pictures in the  /home/ubuntu/face_pic/
a long time after i runned the command,this result was returned:
```
Traceback (most recent call last):
  File "/usr/local/bin/face_recognition", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/face_recognition_cli.py", line 102, in main
    known_names, known_face_encodings = scan_known_people(known_people_folder)
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/face_recognition_cli.py", line 20, in scan_known_people
    img = face_recognition.load_image_file(file)
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 85, in load_image_file
    im = im.convert(mode)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 934, in convert
    self.load()
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFile.py", line 249, in load
    "(%d bytes not processed)" % len(b)
OSError: image file is truncated (2 bytes not processed)
```

### What I Did

run this command:
```
face_recognition --tolerance 0.42 /home/ubuntu/face_pic/ /home/ubuntu/604446db-52e3-4f30-b90f-89c86bb7dfe7
```

**Comment by godcong** [comment]
(no answer)
