### ISSUE TITLE
Error: Reason: image not found

### ISSUE THREAD

**Issue by mikkeld** [ageitgey/face_recognition#9]
* face_recognition version: 1
* Python version: 3.6
* Operating System: Mac OS 10.12.3

I installed dlib following the instructions. When running the recognize_face_in_pictures.py sample file (or any other command) I get the error below:  **Reason: image not found**

```
$user: python3 recognize_faces_in_pictures.py
Traceback (most recent call last):
  File "classify.py", line 1, in <module>
    import face_recognition
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, face_landmarks, face_encodings, compare_faces
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/dlib.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/dlib.so
  Reason: image not found
```

**Comment by mdmedley** [comment]
@mikkeld After you installed ```dlib``` were you able to successfully import the library?

**Comment by mikkeld** [comment]
That seems to be it - I get the following error as well then I run python3 followed by dlib. Any clues on what's causing this?

```
>>> python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'python3' is not defined
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/dlib.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/dlib.so
  Reason: image not found
```

**Comment by ageitgey** [comment]
The actual issue is that it can't find libpng:

```
Library not loaded: @rpath/libpng16.16.dylib
```

I'm guessing you installed it with homebrew but it's not in your library path. Assuming you are using homebrew, can you try:

```
brew link libpng
```

If that doesn't work, make sure libpng is actually installed:

```
brew update && brew upgrade
brew install libpng
brew link libpng
```

If that still doesn't work, maybe reinstall libpng:

```
brew uninstall libpng
brew prune
brew install libpng
```

**Comment by mikkeld** [comment]
Thanks a lot - unfortunately I ran into another library error. I'll update the thread if I find a solution

```
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/__init__.py", line 1, in <module>
    from .dlib import *
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/dlib.so, 2): **Library not loaded: @rpath/libmkl_rt.dylib**
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dlib-19.4.99-py3.6-macosx-10.6-intel.egg/dlib/dlib.so
  Reason: image not found
```

**Comment by mdmedley** [comment]
I'm guessing this is very similar to the earlier issue where it can't find a library, ```libmkl``` to be specific.
```Library not loaded: @rpath/libmkl_rt.dylib```
You'll need to make sure  it is installed

**Comment by mohitpali** [comment]
I tried reinstalling libpng and still did not work. :(

**Comment by jtlz2** [comment]
@mdmedley @mohitpali Just ran into this issue - did you or anyone else success in installing mkl?

**Comment by jtlz2** [comment]
Actually, see #140

**Comment by aseem-hegshetye** [comment]
```
brew doctor
brew prune 
which python3
``` will show you where your python is. Delete anaconda directory if u have any which has your python. Then reinstall python using brew. I dint have to reinstall anything, i just had too many python versions on my mac. python3.6 is the one i prefer. 
Following link helped 
[](https://mattbanderson.com/so-you-hosed-your-mac-os-python-install/)
I ran into this error coz i was learning to set up virtual env. if u need help with that, check following link 
[](https://www.youtube.com/watch?v=N5vscPTWKOk&t=172s)
