### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by zero654655902** [ageitgey/face_recognition#903]
* face_recognition version:1.2.3
* Python version:3.6
* Operating System:ubuntu 16.04
* cuda:9.0.176
* cudnn: 7.0.5

### Description

face_recognition ./known_dir/   ./unkown_dir/   

### What I Did

```
error:
Traceback (most recent call last):
  File "/usr/anaconda3/envs/face/bin/face_recognition", line 10, in <module>
    sys.exit(main())
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/face_recognition/face_recognition_cli.py", line 102, in main
    known_names, known_face_encodings = scan_known_people(known_people_folder)
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/face_recognition/face_recognition_cli.py", line 21, in scan_known_people
    encodings = face_recognition.face_encodings(img)
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/face_recognition/api.py", line 210, in face_encodings
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
  File "/usr/anaconda3/envs/face/lib/python3.6/site-packages/face_recognition/api.py", line 210, in <listcomp>
    return [np.array(face_encoder.compute_face_descriptor(face_image, raw_landmark_set, num_jitters)) for raw_landmark_set in raw_landmarks]
RuntimeError: Error while calling cudnnConvolutionForward( context(), &alpha, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &beta, descriptor(output), output.device()) in file /tmp/pip-install-8guye5if/dlib/dlib/cuda/cudnn_dlibapi.cpp:1007. code: 8, reason: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by ageitgey** [comment]
What GPU are you using? How much memory does it have?

The most likely cases are:
1. You ran out of GPU memory
2. You have an invalid / too old CUDA installation for the GPU you are using

**Comment by zero654655902** [comment]
gpu: 1080ti, 8G
cuda:9.0.176
cudnn:7.0.5

**Comment by YingXiuHe** [comment]
hi, do you have solved this problem, i faced the same question like it.  my computer envs is:  gtx-2070 CUDA9.0 and cudnn 7.1.    Thanks!

**Comment by YingXiuHe** [comment]
i was solved this problem, thanks !
there is my way to solve this problem:
you must keep your Nvidia drivers and your Cuda version, cudnn version matched !! that's really important!
in the end, my computer NVIDIA drivers is 410.93, CUDA is 10.0 and Cudnn is 7.4. GPU is gtx2070
