### ISSUE TITLE
App crashing in jetson nano board (facerec_from_webcam_multiprocessing.py)

### ISSUE THREAD

**Issue by SaddamBInSyed** [ageitgey/face_recognition#904]
* face_recognition version:latest
* Python version:3.6
* Operating System: Jetson Nano

### Description
when i run the **facerec_from_webcam_multiprocessing.py** code , then the app getting crash with the below pasted trace logs.

but **facerec_from_webcam.py** code running in both Gpu and Cpu mode. ( HOG / CNN)

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "facerec_from_webcam_multiprocessing.py", line 86, in process
    frame_process = read_frame_list[worker_id]
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 1

**Comment by ageitgey** [comment]
I just approved a PR that updated the code for that demo. Try grabbing the latest code for that demo from github and running it again.

**Comment by SaddamBInSyed** [comment]
@ageitgey ,

Thanks for the reply.

I have grabbed the updated code and now APP is not crashing but the app looks like extremely slow with Picamera. FPS is 0.2.

I have reduced the frame size too. but no luck.

So how can I improve my FPS to atleast.

highly appreciated your help on this,
