### ISSUE TITLE
Pyharm Terminal pip install face_recognition problem

### ISSUE THREAD

**Issue by ABRAR-HAIDER** [ageitgey/face_recognition#942]
i have anaconda3 and going to run the pip install face_recognition  but have an error "ERROR: Failed building wheel for dlib" on OpenCv Environment

(opencv-env) (venv) C:\Users\Abrar Haider Rajput\PycharmProjects\FirstProject>pip install face_recognition
Requirement already satisfied: face_recognition in c:\fyp\envs\opencv-env\lib\site-packages (1.2.3)
Collecting Click>=6.0 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Requirement already satisfied: Pillow in c:\fyp\envs\opencv-env\lib\site-packages (from face_recognition) (6.1.0)
Requirement already satisfied: face-recognition-models>=0.3.0 in c:\fyp\envs\opencv-env\lib\site-packages (from face_recognition) (0.3.0)
Collecting dlib>=19.7 (from face_recognition)
  Using cached https://files.pythonhosted.org/packages/1e/62/aacb236d21fbd08148b1d517d58a9d80ea31bdcd386d26f21f8b23b1eb28/dlib-19.18.0.tar.gz
Requirement already satisfied: numpy in c:\fyp\envs\opencv-env\lib\site-packages (from face_recognition) (1.17.2)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\FYP\envs\opencv-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\setup.py'"
'"'; __file__='"'"'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"
'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ABRARH~1\AppData\Local\Temp\pip-wheel-jo6rezw2' --python-tag cp37
       cwd: C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\
  Complete output (97 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-
s0nfc6se\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\FYP\envs\opencv-env\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6s
e\dlib\build\lib.win-amd64-3.7 -A x64'
  -- Building for: Visual Studio 14 2015
  -- Selecting Windows SDK version  to target Windows 10.0.17134.
  -- The C compiler identification is MSVC 19.0.23026.0
  -- The CXX compiler identification is MSVC 19.0.23026.0
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: C:/FYP/envs/opencv-env/python.exe (found version "3.7.4")
  -- Found PythonLibs: C:/FYP/envs/opencv-env/libs/Python37.lib
  -- pybind11 v2.2.2
  -- Using CMake version: 3.15.3
  -- Compiling dlib version: 19.18.0
  -- SSE4 instructions can be executed by the host processor.
  -- AVX instructions can be executed by the host processor.
  -- NOTE: Visual Studio didn't have good enough C++11 support until Visual Studio 2015 update 3 (v19.0.24210.0)
  -- So we aren't enabling things that require full C++11 support (e.g. the deep learning tools).
  -- Also, be aware that Visual Studio's version naming is confusing, in particular, there are multiple versions of 'update 3'
  -- So if you are getting this message you need to update to the newer version of Visual Studio to use full C++11.
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of void*
  -- Check size of void* - done
  -- Enabling AVX instructions
  -- Searching for BLAS and LAPACK
  -- Searching for BLAS and LAPACK
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  -- Found Threads: TRUE
  CUDA_TOOLKIT_ROOT_DIR not found or specified
  -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
  -- *** Dlib CUDA support requires C++11 but your compiler doesn't support it. ***
  -- DID NOT FIND CUDA
  -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
  -- C++11 activated.
  CMake Error at CMakeLists.txt:31 (message):
    You have to use a version of Visual Studio that supports C++11.  As of
    December 2017, the only versions that have good enough C++11 support to
    compile the dlib Python API is a fully updated Visual Studio 2015 or a
    fully updated Visual Studio 2017.  Older versions of either of these
    compilers have bad C++11 support and will fail to compile the Python
    extension.  ***SO UPDATE YOUR VISUAL STUDIO TO MAKE THIS ERROR GO AWAY***
  
  
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Abrar Haider Rajput/AppData/Local/Temp/pip-install-s0nfc6se/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/Abrar Haider Rajput/AppData/Local/Temp/pip-install-s0nfc6se/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeError.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "C:\FYP\envs\opencv-env\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\FYP\envs\opencv-env\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\FYP\envs\opencv-env\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\FYP\envs\opencv-env\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\FYP\envs\opencv-env\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\FYP\envs\opencv-env\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\setup.py", line 135, in run
      self.build_extension(ext)
    File "C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\FYP\envs\opencv-env\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\ABRA
RH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\FYP\\envs\\opencv-env\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\
\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: Click, dlib
  Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\FYP\envs\opencv-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\setup.py
'"'"'; __file__='"'"'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n
'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ABRARH~1\AppData\Local\Temp\pip-record-fln5tr1l\install-record.txt' --single-version
-externally-managed --compile
         cwd: C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\
    Complete output (99 lines):
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\ABRARH~1\AppData\Local\Temp\pip-instal
l-s0nfc6se\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\FYP\envs\opencv-env\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc
6se\dlib\build\lib.win-amd64-3.7 -A x64'
    -- Building for: Visual Studio 14 2015
    -- Selecting Windows SDK version  to target Windows 10.0.17134.
    -- The C compiler identification is MSVC 19.0.23026.0
    -- The CXX compiler identification is MSVC 19.0.23026.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: C:/FYP/envs/opencv-env/python.exe (found version "3.7.4")
    -- Found PythonLibs: C:/FYP/envs/opencv-env/libs/Python37.lib
    -- pybind11 v2.2.2
    -- Using CMake version: 3.15.3
    -- Compiling dlib version: 19.18.0
    -- SSE4 instructions can be executed by the host processor.
    -- AVX instructions can be executed by the host processor.
    -- NOTE: Visual Studio didn't have good enough C++11 support until Visual Studio 2015 update 3 (v19.0.24210.0)
    -- So we aren't enabling things that require full C++11 support (e.g. the deep learning tools).
    -- Also, be aware that Visual Studio's version naming is confusing, in particular, there are multiple versions of 'update 3'
    -- So if you are getting this message you need to update to the newer version of Visual Studio to use full C++11.
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Enabling AVX instructions
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    CUDA_TOOLKIT_ROOT_DIR not found or specified
    -- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
    -- *** Dlib CUDA support requires C++11 but your compiler doesn't support it. ***
    -- DID NOT FIND CUDA
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    CMake Error at CMakeLists.txt:31 (message):
      You have to use a version of Visual Studio that supports C++11.  As of
      December 2017, the only versions that have good enough C++11 support to
      compile the dlib Python API is a fully updated Visual Studio 2015 or a
      fully updated Visual Studio 2017.  Older versions of either of these
      compilers have bad C++11 support and will fail to compile the Python
      extension.  ***SO UPDATE YOUR VISUAL STUDIO TO MAKE THIS ERROR GO AWAY***
    
    
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Abrar Haider Rajput/AppData/Local/Temp/pip-install-s0nfc6se/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/Abrar Haider Rajput/AppData/Local/Temp/pip-install-s0nfc6se/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "C:\FYP\envs\opencv-env\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\FYP\envs\opencv-env\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\FYP\envs\opencv-env\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\FYP\envs\opencv-env\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\FYP\envs\opencv-env\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\FYP\envs\opencv-env\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\FYP\envs\opencv-env\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\FYP\envs\opencv-env\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\setup.py", line 135, in run
        self.build_extension(ext)
      File "C:\Users\ABRARH~1\AppData\Local\Temp\pip-install-s0nfc6se\dlib\setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "C:\FYP\envs\opencv-env\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\AB
RARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\FYP\\envs\\opencv-env\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C
:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\FYP\envs\opencv-env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip
-install-s0nfc6se\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\ABRARH~1\\AppData\\Local\\Temp\\pip-install-s0nfc6se\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__
);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ABRARH~1\AppData\Local\Temp\pip-record-fln5tr1l\ins
tall-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by rayavarapuvikram1** [comment]
Same problem for me too
