### ISSUE TITLE
Installation of Face_recognition failed at 91%, "CMD: sudo python setup.py install "

### ISSUE THREAD

**Issue by Stenzil** [ageitgey/face_recognition#958]
* face_recognition version:
* Python version:3.6
* Operating System:Raspbian

### Description

I was trying to install face_recognition by making use of downloaded zip from the official page. 
but then this happened. Can you tell what happened ? and why is it using python 2.7, i wanted it to be in python 3.6 
### What I Did

```
pi@raspberrypi:~/Desktop/face_recognition-1.2.3 $ sudo python setup.py install
```
[ 89%] Building CXX object CMakeFiles/dlib_python.dir/src/shape_predictor.cpp.o
[ 90%] Building CXX object CMakeFiles/dlib_python.dir/src/correlation_tracker.cpp.o
In file included from /usr/include/c++/6/vector:69:0,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/detail/common.h:140,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/pytypes.h:12,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/../dlib/python/pybind_utils.h:6,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/../dlib/python.h:6,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/tools/python/src/opaque_types.h:6,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/tools/python/src/correlation_tracker.cpp:4:
/usr/include/c++/6/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_range_insert(std::vector<_Tp, _Alloc>::iterator, _ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = std::complex<double>*; _Tp = std::complex<double>; _Alloc = std::allocator<std::complex<double> >]’:
/usr/include/c++/6/bits/vector.tcc:616:7: note: parameter passing for argument of type ‘std::vector<std::complex<double>, std::allocator<std::complex<double> > >::iterator {aka __gnu_cxx::__normal_iterator<std::complex<double>*, std::vector<std::complex<double>, std::allocator<std::complex<double> > > >}’ will change in GCC 7.1
       vector<_Tp, _Alloc>::
       ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/6/vector:64:0,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/detail/common.h:140,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/pytypes.h:12,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/cast.h:13,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/attr.h:13,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/external/pybind11/include/pybind11/pybind11.h:43,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/../dlib/python/pybind_utils.h:6,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/dlib/../dlib/python.h:6,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/tools/python/src/opaque_types.h:6,
                 from /tmp/easy_install-mY0L9r/dlib-19.18.0/tools/python/src/correlation_tracker.cpp:4:
/usr/include/c++/6/bits/stl_vector.h: In member function ‘const std::complex<_Tp>* dlib::impl::twiddles<T>::get_twiddles(int) [with T = double]’:
/usr/include/c++/6/bits/stl_vector.h:1375:4: note: parameter passing for argument of type ‘std::vector<std::complex<double>, std::allocator<std::complex<double> > >::iterator {aka __gnu_cxx::__normal_iterator<std::complex<double>*, std::vector<std::complex<double>, std::allocator<std::complex<double> > > >}’ will change in GCC 7.1
    _M_range_insert(__pos, __first, __last, _IterCategory());
    ^~~~~~~~~~~~~~~
[ 91%] Building CXX object CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/dlib_python.dir/build.make:518: recipe for target 'CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o' failed
make[2]: *** [CMakeFiles/dlib_python.dir/src/face_recognition.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    tests_require=test_requirements
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 436, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 680, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 727, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 772, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 699, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 725, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 906, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1145, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1131, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 143, in resume
    type, exc = map(pickle.loads, self._saved)
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
TypeError: __init__() takes at least 3 arguments (1 given)

**Comment by alessiosavi** [comment]
Seems that you have not enough memory in order to compile the software.

Your log lines: `c++: internal compiler error: Killed (program cc1plus)` indicate that the memory is not sufficient for build dlib.

**Comment by Stenzil** [comment]
I tried after dividing the memory, putting more in virtual memory but it still failed

**Comment by alessiosavi** [comment]
Increase the swap may be the solution. I think that `dlib` will be compiled using all the CPU core available. This lead to an higher memory consumption.

**Comment by zainebtlili** [comment]
hi
i can't install face_recognition
sudo pip3 install face_recognition
Downloading/unpacking face-recognition
Cleaning up...
Exception:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
status = self.run(options, args)
File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
File "/usr/lib/python3/dist-packages/pip/index.py", line 292, in find_requirement
elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in is_prerelease
return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in 
return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log
