### ISSUE TITLE
Error while installing on CentOS 7

### ISSUE THREAD

**Issue by dktechindia** [ageitgey/face_recognition#965]
* face_recognition version: Latest
* Python version: 3.8
* Operating System: CentOS7

### Description

I followed the  installation instructions available in the repository . Tried to install dlib and it also failed. was able to install cmake but it is not installing other components.

### What I Did

```
$ sudo pip3 install face_recognition
Collecting face_recognition
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/site-packages (from face_recognition) (6.2.1)
Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.8/site-packages (from face_recognition) (0.3.0)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.8/site-packages (from face_recognition) (7.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/site-packages (from face_recognition) (1.17.3)
Collecting dlib>=19.7
  Using cached https://files.pythonhosted.org/packages/1e/62/aacb236d21fbd08148b1d517d58a9d80ea31bdcd386d26f21f8b23b1eb28/dlib-19.18.0.tar.gz
Installing collected packages: dlib, face-recognition
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d00i72gh/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d00i72gh/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ynn72kjh/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-d00i72gh/dlib/
    Complete output (54 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "/usr/local/bin/cmake", line 8, in <module>
        sys.exit(cmake())
      File "/usr/local/lib/python3.8/site-packages/cmake/__init__.py", line 46, in cmake
        raise SystemExit(_program('cmake', sys.argv[1:]))
      File "/usr/local/lib/python3.8/site-packages/cmake/__init__.py", line 42, in _program
        return subprocess.call([os.path.join(CMAKE_BIN_DIR, name)] + args)
      File "/usr/local/lib/python3.8/subprocess.py", line 340, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/cmake/data/bin/cmake'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d00i72gh/dlib/setup.py", line 223, in <module>
        setup(
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-d00i72gh/dlib/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/tmp/pip-install-d00i72gh/dlib/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d00i72gh/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d00i72gh/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ynn72kjh/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

```

**Comment by alessiosavi** [comment]
Use a `virtualenv` with python 3.7.3.
Seems that the library does not support yet the 3.8 version of python.
