### ISSUE TITLE
Error when using the trainer script

### ISSUE THREAD

**Issue by MiguelAlatorre0145** [ageitgey/face_recognition#969]
* Python version: 3.6.8
* Operating System: Ubuntu 18.04

Hello all, I want to start off by saying I'm still fairly new to python so I apologize if I don't fully understand things. I plan to have a Khadas VIM3 (single board computer) run facial recognition on some recordings from a local server. The thing is, not many faces are seen / correctly identified, so I decided to try and train it. 
The problem arises when I run the actual script. For what ever reason, the ```clf.fit(encodings, names)``` section always returns an error, saying that it expects a number, not a string. I'm really not sure what the error here is. Here is the actual output : 
```
Traceback (most recent call last):
  File "Training.py", line 65, in <module>
    clf.fit(encodings,names)
  File "/usr/lib/python3/dist-packages/sklearn/svm/base.py", line 187, in fit
    fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
  File "/usr/lib/python3/dist-packages/sklearn/svm/base.py", line 254, in _dense_fit
    max_iter=self.max_iter, random_seed=random_seed)
  File "sklearn/svm/libsvm.pyx", line 58, in sklearn.svm.libsvm.fit
TypeError: must be real number, not str
```

Any and all help is much appreciated!

**Comment by SaddamBInSyed** [comment]
Hi there,
Did you solve this?
if so what causes this pbm?

please advise
@ageitgey 
@AnandBaburajan

**Comment by FedericoLanzani** [comment]
Hi! I swear you are doing great with your python projects! 
Have you made any changes to the exemple code?
If so, can you share it?

Anyway:
Try to change the "gamma="scale"" parameter when initializing the SVC from **"scale"** to **0.001**:
clf = svm.SVC(gamma=0.001)`

If this doesn't work try to share the code.

Bye 👋
