### ISSUE TITLE
Error: import face_recognition 

### ISSUE THREAD

**Issue by lissettecarlr** [ageitgey/face_recognition#972]
* face_recognition version: 1.2.3
* Python version:3.7
* Operating System: Pi4

### Description
I can't import face_recognition
```
pi@FFFpi:~/camera/opencv $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/pi/.local/lib/python3.7/site-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: /home/pi/.local/lib/python3.7/site-packages/dlib.cpython-37m-arm-linux-gnueabihf.so: file too short
>>> 
KeyboardInterrupt
```
```
pi@FFFpi:~/camera/opencv $ python3 --version
Python 3.7.3
pi@FFFpi:~/camera/opencv $ pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
pi@FFFpi:~/camera/opencv $ pip3 install face_recognition
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: face_recognition in /home/pi/.local/lib/python3.7/site-packages (1.2.3)
Requirement already satisfied: face-recognition-models>=0.3.0 in /home/pi/.local/lib/python3.7/site-packages (from face_recognition) (0.3.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from face_recognition) (1.16.2)
Requirement already satisfied: dlib>=19.7 in /home/pi/.local/lib/python3.7/site-packages (from face_recognition) (19.18.0)
Requirement already satisfied: Click>=6.0 in /usr/lib/python3/dist-packages (from face_recognition) (7.0)
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from face_recognition) (5.4.1)
```
```
pi@FFFpi:~/camera/opencv $ pip3 list
dlib    19.18.0   
face-recognition    1.2.3      
face-recognition-models  0.3.0 
```

```
pi@FFFpi:~/camera/opencv $ sudo python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import face_recognition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'face_recognition'
>>> 

```

### What I Did
```
python3
import face_recognition

sudo  python3
import face_recognition
```

**Comment by akzuki** [comment]
I used to get the `ModuleNotFoundError: No module named 'face_recognition'` error and for me, it's because I use Anaconda to install different Python versions (3.5, 3.6, 3.7 etc) and when I run `python3`, it pointed to the version that doesn't have `face_recognition` package.
If I run it with the correct version that has the package e.g `python3.5 my_script.py` it'll work just fine. So you might want to have a look into that.

**Comment by lissettecarlr** [comment]
I don't know why two commands have different results
(python3  and sudo python3)

**Comment by alessiosavi** [comment]
Seems that you are missing `cython`.

Try with `pip install Cython`

**Comment by zainebtlili** [comment]
hi 
i can't install face_recognition 
 sudo pip3 install face_recognition
Downloading/unpacking face-recognition
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
  File "/usr/lib/python3/dist-packages/pip/util.py", line 739, in <listcomp>
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log

**Comment by you202a** [comment]
I HAVE SOME PROBLEM .....!!!!!!! 
IS NOT WORKING.....

**Comment by jmcausing** [comment]
Same problem!
