### ISSUE TITLE
I couldn't install face_recognition module in my PC. 

### ISSUE THREAD

**Issue by Arrow023** [ageitgey/face_recognition#989]
ERROR: Complete output from command 'C:\Users\HP\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\HP\AppData\Local\Temp\pip-wheel-sle6n2cg' --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\Users\HP\Anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\build\lib.win-amd64-3.7 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:3 (project):
    Generator
  
      NMake Makefiles
  
    does not support platform specification, but platform
  
      x64
  
    was specified.
  
  
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
  CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/HP/AppData/Local/Temp/pip-install-sm7xwey_/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "C:\Users\HP\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\HP\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\HP\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Users\HP\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\HP\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\HP\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\setup.py", line 135, in run
      self.build_extension(ext)
    File "C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\setup.py", line 172, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\Users\HP\Anaconda3\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\Users\\HP\\Anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, face-recognition
  Running setup.py install for dlib ... error
    ERROR: Complete output from command 'C:\Users\HP\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HP\AppData\Local\Temp\pip-record-ejzg959g\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\build\lib.win-amd64-3.7 -DPYTHON_EXECUTABLE=C:\Users\HP\Anaconda3\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\build\lib.win-amd64-3.7 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Generator
    
        NMake Makefiles
    
      does not support platform specification, but platform
    
        x64
    
      was specified.
    
    
    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/HP/AppData/Local/Temp/pip-install-sm7xwey_/dlib/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "C:\Users\HP\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\HP\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\HP\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\HP\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\HP\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\HP\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\HP\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\HP\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\setup.py", line 135, in run
        self.build_extension(ext)
      File "C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\setup.py", line 172, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "C:\Users\HP\Anaconda3\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\Users\\HP\\Anaconda3\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "'C:\Users\HP\Anaconda3\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-sm7xwey_\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\HP\AppData\Local\Temp\pip-record-ejzg959g\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HP\AppData\Local\Temp\pip-install-sm7xwey_\dlib\

**Comment by deepa042008** [comment]
**PROBLEM DESCRIPTION** 
I am trying to follow  https://www.youtube.com/watch?v=QSTnwsZj2yc

I have done a conda activate my_env and then executed face_recognition to compare the known and unknown folders. 
It is not recognizing this command and says 
Fatal error in launcher: Unable to create process using '"h:\python37\python.exe
"  "H:\Python37\Scripts\face_recognition.exe" D:\Users\srt1\exercise\known D:\Us
ers\srt1\exercise\unknown'
I dont know much about docker, yml _init_.py (packaging)

Pls advise/help

**Background**
I have copied path and unzipped face_recognition and stored in 
D:\Users\srt1 as face_recognition-master
**Details**
I have a Windows 7 The conda prompt is D drive Python and all other prompt is H drive
The User variable Path 
H:\anc;H:\anc\Library\mingw-w64\bin;H:\anc\Library\usr\bin;H:\anc\Library\bin;H:\anc\Scripts;H:\Python37\Scripts\;H:\Python37\;H:\python\python3\Scripts\;H:\python\python3\;H:\python\python3\cmake\cmake-3.16.0-rc4-win64-x64\bin;

The system variable path is 
D:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\system32\Wbem;D:\Program Files (x86)\Intel\iCLS Client\;D:\Program Files\Intel\iCLS Client\;D:\Program Files\Dell\DW WLAN Card;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;D:\Program Files\WIDCOMM\Bluetooth Software\;D:\Program Files\WIDCOMM\Bluetooth Software\syswow64;D:\Program Files\Intel\Intel(R) Management Engine Components\DAL;D:\Program Files\Intel\Intel(R) Management Engine Components\IPT;D:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;D:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;D:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;D:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;D:\Program Files (x86)\QuickTime\QTSystem\;E:\PuTTY\;e:\cygwin641\;h:\mys\mysql-8.0.17-winx64\bin;H:\python\python3\cmake\cmake-3.16.0-rc4-win64-x64\bin;

**Comment by SiyangXie** [comment]
`pip install cmake` or `pip3 install cmake` if you're on python 3.x
